### ISSUE TITLE
High CPU usage using on-disk storage

### ISSUE THREAD

**Issue by madpsy** [allinurl/goaccess#523] opened 2016-09-21 10:18 UTC
I run GoAccess (1.0.2) against a log file which has a rate of around 4 entries per second. I have one client connected to websockets for the real-time stats page. Goaccess is using tokyo cab DB files.

What I find is that the goaccess process consumes around 80% of 1 (faily beafy) CPU core at this rate. 

Is the 'high' CPU usage expected at this rate or could something be amiss?

Thanks

**Comment by allinurl** [comment] 2016-09-21 12:10
Just took a snapshot of rt.goaccess.io using the default storage (in-memory) v1.0.2, averaging 6 reqs/sec and 41 clients connected at that particular time, goaccess is consuming around 5-6%.

I'll build GoAccess with on-disk support and I'll post back. Thanks

**Comment by allinurl** [comment] 2016-09-21 23:16
I was trying to reproduce this using the on-disk storage and I was just able to hit 35% of the CPU (4 core processor) with 1 client connected and ~20 hits/sec. Apache was actually consuming more CPU when serving these requests.

Have you tried restarting goaccess and see if that helps? Also, did get the above output from strace? I ran strace and I couldn't see any `pread()` calls.

**Comment by allinurl** [comment] 2016-09-21 23:39
I just noticed that the `pread()` calls are done in tokyocab. What version are you using?

**Comment by madpsy** [comment] 2016-09-22 08:07
GoAccess - 1.0.2
libtokyocabinet9 - 1.4.48

Yeah the pread() calls are seen in an strace. They literally show as fast as the terminal will allow which probably explains the CPU usage.

I restarted goaccess but it does the same.

**Comment by madpsy** [comment] 2016-09-22 08:40
I tried setting:

keep-db-files false 
load-from-disk false

But the pread() and high CPU usage still occured after restart. Not sure why (based on what you said), the pread()'s were still being called given btree shouldn't be in use (it took a good few seconds to process the log file on start, confirming it wasn't using the btree DB).

FYI the log file is currently 164MB / 290609 lines

**Comment by allinurl** [comment] 2016-09-22 13:37
Let me play with this again and see if I can replicate it. Would you be able to post your config file? Also, can I ask you which version of ubuntu/debian are you using (assuming you installed tokyo using apt-get)?  Thanks

**Comment by madpsy** [comment] 2016-09-22 13:43
Sure - it's Ubuntu 14.04

Run with:

/usr/local/bin/goaccess -o /var/www/html/goaccess/index.html --real-time-html --ws-url=xxxxxxxxxx:7891 --addr xxx.xxx.xxx.xxx

Config is:

```
log-file /var/log/apache2/site_access.log
time-format %H:%M:%S
date-format %d/%b/%Y
log-format [%d:%t %^] %h %v %^ %^ "%r" %s %b "%R" "%u"
config-dialog false
color-scheme 1
hl-header true
no-color false
no-column-names false
no-progress false
with-mouse false
no-csv-summary false
all-static-files false
static-file .css
static-file .js
static-file .jpg
static-file .png
static-file .gif
static-file .ico
static-file .jpeg
static-file .pdf
static-file .txt
static-file .csv
static-file .zip
static-file .mp3
static-file .mp4
static-file .mpeg
static-file .mpg
static-file .exe
static-file .swf
static-file .woff
static-file .woff2
static-file .xls
static-file .xlsx
static-file .doc
static-file .docx
static-file .ppt
static-file .pptx
static-file .iso
static-file .gz
static-file .rar
static-file .svg
static-file .bmp
static-file .tar
static-file .tgz
static-file .tiff
static-file .tif
static-file .ttf
static-file .flv
agent-list false
http-method true
http-protocol true
no-query-string false
no-term-resolver false
real-os true
with-output-resolver false
444-as-404 false
4xx-to-unique-count false
double-decode false
ignore-crawlers false
ignore-panel REFERRERS
ignore-panel KEYPHRASES
keep-db-files true
load-from-disk true
compression zlib
db-path /var/www/html/goaccess/goaccess-db/
```

**Comment by allinurl** [comment] 2016-09-25 21:39
I've been testing this for some time using the config posted above and with a similar log as yours of ~155MB. I noticed that tokyocabinet will perform a lot of reads when it loads all of the records from disk, this will take a few seconds using at least 1 core (depending on the number of records to read) and then it will go back to low CPU usage.

Also, I noticed that you are using `keep-db-files` and `load-from-disk`. If you are passing a file to read `-f`, then goaccess will store again all of the records, so you will end up with twice the amount of total requests. If you do this multiple times, tokyocabinet will have to do a bunch of reads and those may be the ones you are seeing. Take a look at the man page's [**examples**](https://goaccess.io/man#examples) for more details on processing logs incrementally without appending data.

So I'm thinking this could be an isolated issue since I was not able to reproduce the infinite loop of preads, it could be a corrupt db file as mentioned in [**here**](https://git.io/vixs6), I'd recommend deleting all files under `/var/www/html/goaccess/goaccess-db/` and give it a shot.

FWIW, here's the output I'm getting:

![out avi](https://cloud.githubusercontent.com/assets/5005367/18818411/149b5a56-833e-11e6-8527-82224c7bee62.gif)

**Comment by madpsy** [comment] 2016-09-26 12:51
Thanks for the detailed response...

I'll try both removing the DB files and also try with a newer version of tokyocab on Ubuntu 16.04.

P.S. I tried creating a ttygif but within a couple seconds of strace output it created a 20MB gif so aborted that idea!

**Comment by madpsy** [comment] 2016-09-26 12:58
I've abondoned using the DB for now and it's running fine. FYI the DB directory was around 700MB in size.

**Comment by allinurl** [comment] 2016-09-27 00:45
A 700MB directory for a 164MB log size, sounds like `keep-db-files` along with `load-from-disk` was storing duplicate records and thus the large number of `preads`. 

If you still need data persistence, I'd recommend parsing the log once and use `keep-db-files` and `load-from-disk`. However, if you just need to read persisted data, use `keep-db-files` and `load-from-disk` but do not use `-f`. 

Issue #334 plans to address the duplicate parsing.

Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2016-09-27 00:45 UTC
