### ISSUE TITLE
Piping content to `goaccess --no-global-config` causes no time format error

### ISSUE THREAD

**Issue by mqudsi** [allinurl/goaccess#840] opened 2017-07-13 21:28 UTC
Under goaccess 1.2:

`goaccess --no-global-config -f /tmp/somelog` works
`cat /tmp/somelog | goaccess --no-global-config` crashes with the following:

```
GoAccess - version 1.2 - May 18 2017 01:56:07
Config file: No config file used

Fatal error has occurred
Error occured at: src/goaccess.c - set_curses - 1394
No time format was found on your conf file.

```

**Comment by allinurl** [comment] 2017-07-13 21:38
When data is piped, you need to set it in a config file or simply on the command line such as:

    cat /tmp/somelog | goaccess --no-global-config --log-format=COMBINED

or create a new config file, specify the log/date/time formats and use:

    cat /tmp/somelog | goaccess -p /path/to/copied/goaccess.new.conf

**Comment by allinurl** [comment] 2017-07-15 19:15
Any updates on this?

**Comment by allinurl** [comment] 2017-07-17 13:50
Closing this. Feel free to reopen it as needed.

**Closed by allinurl** 2017-07-17 13:50 UTC
Labels: log/date/time format, question

**Comment by mqudsi** [comment] 2017-07-17 17:05
Only repository contributors can re-open issues, but there is no need to re-open this.
I was basing my usage off the example from the readme:
```
# tail -f access.log | goaccess -
```

I guess the only bug here is in the readme? Is that intended to be used with an existing `goaccess` session in the background?

**Comment by allinurl** [comment] 2017-07-17 17:49
That's a good point. No, it's not intended to be use with an existing session. I can add a note to the examples section on README.md that piping data into goaccess won't prompt the log config dialog and therefore it's required to specify it on a config file or through the command line. Thanks for pointing that out.

**Comment by allinurl** [comment] 2017-07-17 17:57
A [**note**](https://github.com/allinurl/goaccess#examples) has been added. Thanks again!

**Comment by mqudsi** [comment] 2017-07-21 15:32
One more question: shouldn't the behavior of 

`cat file.log | goaccess --no-global-config` 

match the behavior of 

`goaccess --no-global-config -f file.log` ?

The latter prompts the user to pick a format, but the former throws an error.

**Comment by allinurl** [comment] 2017-07-21 15:46
I agree, however, when data is piped into goaccess, it reads it from stdin. The issue is that at that point handling keyboard sequences and stdin at the same time becomes a bit of a mess. 

Actually v1.2 it's duplicating file descriptors so it doesn't get in the way of curses' normal reading stdin, so probably adding this functionality shouldn't be too much of a pain. It would be nice to revise this and see what can be done to handle both.

**Comment by allinurl** [comment] 2017-07-21 15:47
For the record, [**here's**](https://github.com/allinurl/goaccess/blob/master/src/goaccess.c#L1201) the code I mentioned above.

**Comment by mqudsi** [comment] 2017-07-21 15:48
Interesting, I never thought of that! 

I use the combined log format so I don't know the answer to this question: are there any self-documenting log formats and does goaccess support automatically detecting the log format from those files? If the answer is no, would it make things easier to not touch the pipe descriptor until you've asked the user for log format if no format has been specified at the command-line?

**Comment by allinurl** [comment] 2017-07-21 18:59
That's correct, it doesn't automatically detect the log format (It's on the to-do list). 

I'm not sure if I follow, and please correct me if I'm wrong, but you are saying that we should display the log-format dialog when data is piped, read the entered format and then read data from the pipe?
