### ISSUE TITLE
Running goaccess locally and tailing log from remote server

### ISSUE THREAD

**Issue by Jamalc0m** [allinurl/goaccess#1282] opened 2018-10-25 13:44 UTC
When I try the following command, it doesn;t work, it just keep stuck on parsing [0]

```
Hunter:goaccess-1.2 hunter$ ssh root@xxxxxx 'cat /var/log/apache2/access.log' | goaccess -o report.html --real-time-html --ws-url=127.0.0.1
Parsing... [0] [0/s]s password: Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Permission denied, please try again.
Parsing... [0] [0/s]s password: Parsing... [0] [0/s]
Permission denied, please try again.
Parsing... [0] [0/s]s password: Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
Parsing... [0] [0/s]
^Crsing... [0] [0/s]
SIGINT caught!
Closing GoAccess...
```

**Comment by Jamalc0m** [comment] 2018-10-25 13:51
@allinurl

**Comment by allinurl** [comment] 2018-10-25 14:04
Have yo checked if you are getting data from your pipe? e.g.,

    ssh -t -t root@xxxx 'tail -f /var/log/apache2/access.log'

Please try also appending a single dash to goaccess. By default it will run in localhost

    ssh -t -t root@xxxx 'tail -f test.log | goaccess -o test.html --real-time-html -'

**Comment by Jamalc0m** [comment] 2018-10-25 14:08
> Have yo checked if you are getting data from your pipe? e.g.,
> 
> ```
> ssh -t -t root@xxxx 'tail -f /var/log/apache2/access.log'
> ```
> Please try also appending a single dash to goaccess. By default it will run in localhost
> 
> ```
> ssh -t -t root@xxxx 'tail -f test.log | goaccess -o test.html --real-time-html -'
> ```

First command is working, second one no!

**Comment by Jamalc0m** [comment] 2018-10-25 14:09
It keeps stuck at parsing  ..[0]

**Comment by gaohaoning** [comment] 2018-11-01 09:11
same problem when starting the second goaccess process on one host.
(the first process works normally)

**Comment by 0Styless** [comment] 2019-05-07 14:59
I have the exact same problem, so I can confirm that too.

```
ssh localhost 'tail -f /var/log/httpd/access_log' | goaccess - -a -o /var/www/report.html --log-format=COMBINED --real-time-html --port=7890 --ssl-cert=/etc/pki/tls/certs/cert.crt --ssl-key=/etc/pki/tls/private/key.key --fifo-in=/tmp/goaccess.in --fifo-out=/tmp/goaccess.out
```

This is just a very small logfile and there are hardly any new requests during the parsing process. I have let it stand there for hours and it still says:

```
Parsing... [10] [1/s]]
Parsing... [10] [1/s]
Parsing... [10] [1/s]
Parsing... [10] [1/s]
Parsing... [10] [1/s]
Parsing... [10] [1/s]
Parsing... [10] [1/s]
Parsing... [10] [1/s]
Parsing... [10] [1/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
Parsing... [10] [0/s]
```


```
$ goaccess --version
GoAccess - 1.3.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=legacy
  --with-openssl
```

So is there any suggestion to this?

**Comment by allinurl** [comment] 2019-05-09 12:07
Thanks for the reminder. I haven't had a chance to look at this. A workaround right now is to use a local file and read that file with goaccess.

**Comment by 0Styless** [comment] 2019-06-24 16:38
Hey @allinurl 

anything new to this? Sadly, local files are not really a great workaround.

**Comment by Jamalc0m** [comment] 2019-06-25 05:34
Right, @allinurl if you could please fix this issue would be appreciated.

**Comment by liabilityman** [comment] 2019-07-19 02:59
Having the same issue. Seems to be that Goaccess is starting before you get a chance to enter the ssh password.

Haven't tested, but I imagine if you created a passwordless account you could ssh with (with restricted access of course) that it would work as the password prompt wouldn't be needed.

**Comment by 0Styless** [comment] 2019-07-22 18:51
@liabilityman I can't confirm that, even doesn't work with ssh keys.

**Comment by liabilityman** [comment] 2019-07-23 03:52
@0Styless This is the command I used, see if it works for you:

`ssh -t username@server 'tail -f -n +1 /var/log/nginx/access.log' | goaccess -o /path/to/report.html --real-time-html -`

**Comment by allinurl** [comment] 2020-11-25 03:00
Closing this. I can confirm that it works fine in v1.4.2 if outputting an HTML report and using `--real-time-html` along the additional dash `-`. Please note that you need to use [ssh with keys](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-2).

**Comment by allinurl** [comment] 2020-11-25 03:01
BTW, feel free to reopen it if needed.

**Closed by allinurl** 2020-11-25 03:00 UTC
Labels: html report, log-processing, question, websocket-server

**Comment by breck7** [comment] 2022-08-30 08:18
I hit a similar issue where goaccess was hanging at `Parsing... [0] [0/s]`. I am sharing my solution in case others stumble upon this issue from Google like I did.

I was trying to aggregate many days into one with this command:

`sudo zcat -f /var/log/nginx/access.log* | goaccess -o /var/www/html/nginxDailyAll.html --log-format=COMBINED`

The solution was to just `su` to root and then run the command (dropping the sudo). Easy enough.

It seems like for some reason it was getting hung on the `sudo` part.

**Comment by allinurl** [comment] 2022-08-30 12:30
@breck7 Thanks for sharing those findings!
