### ISSUE TITLE
Can't install the latest version 1.6.5 on Ubuntu 18.04 (bionic)

### ISSUE THREAD

**Issue by marlonanjos** [allinurl/goaccess#2410] opened 2022-11-04 10:44 UTC
The latest version 1.6.5 added the dependency package libncursesw6 which is not available on Ubuntu 18.04LTS Bionic. 

```
The following packages have unmet dependencies:
 goaccess : Depends: libncursesw6 (>= 6.0) but it is not installable
```
```
Package libncursesw6 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libncursesw6' has no installation candidate
```

The version 1.6.4 was was running fine on the same server.

Thank you,
Marlon

**Comment by PantheaEU** [comment] 2022-11-04 16:12
I can confirm this.

Has the exact same problem on several Ubuntu 18.04 servers when trying to upgrade from 1.6.4 to 1.6.5

**Comment by allinurl** [comment] 2022-11-04 16:38
Thanks for the heads up on this. The issue should be fixed.

Please let me know if that solves the issue on your end.

**Comment by PantheaEU** [comment] 2022-11-04 16:52
Issue seems to be resolved.
1.6.5 installs and works fine on all my instances now.

**Comment by marlonanjos** [comment] 2022-11-04 17:08
Can confirm, the issue is fixed. 


Thank you @allinurl.

**Comment by allinurl** [comment] 2022-11-04 17:09
Thank you all. Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2022-11-04 17:09 UTC
Labels: dependencies, debian-repo
