### ISSUE TITLE
Token for '%h' specifier is NULL. - nginx access log

### ISSUE THREAD

**Issue by sundedo** [allinurl/goaccess#1478] opened 2019-06-13 20:46 UTC
I've scoured over previous format questions but still can't find the right log-format for our nginx access.log. Here is the sample log:

`127.0.0.1 - - [13/Jun/2019:20:40:16 +0000] "POST /soap3/api.php HTTP/1.1" 200 557 "-" "PHP-SOAP/5.6.35"`

We have tried the following log-formats:

log-format %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u"

log-format %h %^[%d:%^] "%r" %s %b "%R" "%u"

Still get this error:

`/bin/goaccess9659] [29659/s]

Parsed 10 lines producing the following errors:
```

Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.

Format Errors - Verify your log/date/time format`
```

**Comment by allinurl** [comment] 2019-06-16 02:39
goaccess access.log --log-format=COMBINED

**Comment by allinurl** [comment] 2019-07-02 01:57
Any updates on this?

**Comment by allinurl** [comment] 2019-07-02 01:58
Closing this, feel free to reopen it if needed.

**Closed by allinurl** 2019-07-02 01:58 UTC
Labels: log/date/time format, question

**Comment by holiday25** [comment] 2024-05-07 06:22
hi 
my log file
172.16.18.57 - - [03/May/2024:13:53:30 +0000] "GET / HTTP/1.1" 200 615 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
172.16.18.57 - - [03/May/2024:13:53:30 +0000] "GET /favicon.ico HTTP/1.1" 404 555 "http://172.16.18.163/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
172.16.18.57 - - [03/May/2024:13:55:18 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.16.18.57 - - [03/May/2024:13:55:38 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.16.18.57 - - [03/May/2024:13:55:43 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.16.18.57 - - [03/May/2024:13:59:14 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.16.18.57 - - [03/May/2024:13:59:18 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.81.0" "-"
172.16.18.57 - - [03/May/2024:14:01:32 +0000] "GET /index.html HTTP/1.1" 200 615 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
172.16.18.57 - - [03/May/2024:14:01:35 +0000] "GET /index.html HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"


my conf file 

log-file /opt/log/access.log
output report.html
real-time-html true
log-format COMMON
time-format %H:%M:%S
date-format %d/%b/%Y

command that i run

command: ["zcat -f /opt/log/access.log.1.gz | goaccess -"]

i run this command using ansible 
but i still got error:

==1== Token for '%h' specifier is NULL.
==1== Token for '%h' specifier is NULL.
==1== Token for '%h' specifier is NULL.
==1== Token for '%h' specifier is NULL.
==1== Token for '%h' specifier is NULL.
==1== Token '�0fl�}�c�j*���i&���Od�Ϛ^?n����t�d�:�����fڭ�i����˧����lRV�����/W����' doesn't match specifier '%h'


i also tried to change "COMMON">"COMBINED"
but nothing changes
can u help me

**Comment by holiday25** [comment] 2024-05-07 06:30
also if i only parse current access.log it is not getting such error , although .gz file and access.log is the same

**Comment by allinurl** [comment] 2024-05-08 02:26
It seems to be using the COMBINED log format. When parsing a gzipped log file, make sure to use zcat. Check the [man page](https://goaccess.io/man#examples) for usage examples.

    # zcat access.log.*.gz | goaccess access.log - --log-format=COMBINED -o report.html

**Comment by holiday25** [comment] 2024-05-08 06:04
here just simple example 

zcat access.log.*.gz | goaccess access.log -

and u give me this exapmple: # zcat access.log.*.gz | goaccess access.log - --log-format=COMBINED -o report.html
but on the docs i found out this note 
```
Note: Piping data into GoAccess won't prompt a log/date/time configuration dialog, you will need to previously define it in your configuration file or in the command line.
```
so i define it in conf file.
ok, the problem is which format of logs do i need to use to fix this error?
thanks for help)

**Comment by allinurl** [comment] 2024-05-14 02:06
I've tested the following with the sample log you provided, and it works fine for me:

    # goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --tz=America/New_York --date-spec=min

**Comment by holiday25** [comment] 2024-05-14 12:05
dude it works when u execute it locally. but i am trying to run all of this stuff with ansible and i deploy goaccess using docker , so when i run this command 
 zcat access.log.*.gz | goaccess access.log -
 
 inside the container i got error
 ==1== Token for '%h' specifier is NULL.

**Comment by allinurl** [comment] 2024-05-15 00:04
@holiday25 I'd hop into the container and check if you can pull up the real log. Then, try running GoAccess from there. Seems like there might be a setup hiccup with either Ansible or Docker on your end.
