### ISSUE TITLE
HTTP Status Code Chart with Time information

### ISSUE THREAD

**Issue by ajinugroho85** [allinurl/goaccess#1136] opened 2018-06-06 03:49 UTC
Hi, is it possible to enhance the HTTP STATUS CODE chart by adding the time, 
Looks like combination of HTTP STATUS CODE Chart and TIME DISTRIBUTION Chart,

To inform that 502 status code happen in what time, to identify the behavior of application.
and inform also the success rate, between status code 200 and non 200, 

Thanks

**Comment by allinurl** [comment] 2018-06-06 11:42
I think #117 will address this in the sense that you will be able to filter by time and therefore displaying only the status codes for that particular time range.

**Comment by ajinugroho85** [comment] 2018-06-08 16:27
You mean this features already available?

**Comment by allinurl** [comment] 2018-06-09 04:13
It's not available yet. I'll close this as it's a duplicate of #117.

**Closed by allinurl** 2018-06-09 04:13 UTC
Labels: duplicate, enhancement, html report
