### ISSUE TITLE
Docker repo not found from README

### ISSUE THREAD

**Issue by if-kyle** [allinurl/goaccess#688] opened 2017-03-15 16:18 UTC
Hello,

It seems the docker repo does not exist from the README.

`docker run --restart=always -d -p 80:8080 -v "/home/user/data:/srv/data" allinurl/goaccess`

`docker pull allinurl/goaccess` returns "repository allinurl/goaccess not found".

I was able to create the docker image after cloning the repo and running `docker build -t goaccess .` from the top dir of the repo.

Might also be good to add a section about Docker to https://goaccess.io/download 

Thanks for this project, I've used it for about a year now and have been very happy with it, and look forward to trying out the live view.

**Comment by allinurl** [comment] 2017-03-15 16:51
Thanks for reporting this. I'll try to reproduce this. 

@julianxhokaxhiu do you know what might be the issue?

**Comment by julianxhokaxhiu** [comment] 2017-03-15 19:31
Hi  @allinurl that instruction was left because I thought you would create your automated build configuration in Docker with your username :)

If not, please do it, so people can always download the latest and greatest based on your commits :D See https://docs.docker.com/docker-hub/builds/

**Comment by allinurl** [comment] 2017-03-21 01:25
OK, so I've pushed the [**official build**](https://hub.docker.com/r/allinurl/goaccess/) of GoAccess, it should let you run the command specified above.

I also added a section to the [**download page**](https://goaccess.io/download#docker). Let me know how it goes. Thanks!

**Comment by julianxhokaxhiu** [comment] 2017-03-21 07:09
Why not automated build?

**Comment by allinurl** [comment] 2017-03-21 12:27
@julianxhokaxhiu odd, I thought I had set up an automated build. I just did [**here**](https://hub.docker.com/r/allinurl/goaccess/), please take a look it and let me know what you think.

**Comment by julianxhokaxhiu** [comment] 2017-03-21 18:34
Now it looks good :) well done!

**Comment by allinurl** [comment] 2017-03-23 02:43
Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2017-03-23 02:43 UTC
Labels: build
