### ISSUE TITLE
The connection to ws: //hots: 7890 / was interrupted while the page was being loaded.

### ISSUE THREAD

**Issue by Nitrosito** [allinurl/goaccess#630] opened 2017-01-20 12:25 UTC
Hi

I mounted on my computer goaccess and works fine.

I actually mounting a GoAccess on the production enviroment. Deploy on a Server (we using this server as Apache Proxy) , 

I create a VirtualHost:

```
<VirtualHost *:80>
        ServerName xxxxxxxxx
        LogLevel info
        CustomLog /var/log/apache2/goaccess.log vhost_combined
        DocumentRoot "/var/www/"

        <Location />
                  Order Deny,Allow
                  Deny from all
                  Allow from 127.0.0.1 ::1
                  Allow from localhost
                  Allow from 192.168
        </Location>
</VirtualHost>
```

And execute

    goaccess  -f /var/log/apache2/access-test.log -a -o /var/www/index.html --real-time-html --ws-url=xxxxxx

Goaccess parsing files, create a HTML , but dont update this any more. And Firefox Console (tried too on chrome) see:

> The connection to ws: //hots: 7890 / was interrupted while the page was being loaded.

Telnet to 7890   (my computer > go access ) works ok

Same deploy on my machine and apache proxy server, but goaccess on server dont work..

Thanks and regards

**Comment by Nitrosito** [comment] 2017-01-20 12:41
¿I can create a dedicated goaccess server , and send the logs from apache proxy > go access machine server?

how send logs from apache server to goaccess standalone server? via web socket?
¿¿ goaccess -f /var/log/apache2/access-test.log -a -o /var/www/index.html --real-time-html --ws-url=dedicatedservergoaccess??

other question... I like save ALL logs stadistic, but with logrotate enabled (erase logs after 7 days)
--keep-db-files and --load-from-disk , and custom directory to keep db files?

thanks

**Comment by allinurl** [comment] 2017-01-20 18:08
Sounds like a server configuration issue. A couple of things.

1. Make sure the port 7890 from your browser is opened.
2. Please try setting `--ws-url` to the same host name as the one being used in the browser URL. It may be similar to issue #583. 
3. You can try building from [**development/github**](https://goaccess.io/download#build), I pushed a [commit](https://github.com/allinurl/goaccess/commit/446c83d75d7002a3f12b2a887434ff96d1b2df80?diff=unified) per #590 for the upcoming version that simplifies the connection from the browser to the server, so you don't need to use `--ws-url` anymore. Just run it as:

```
goaccess -f /var/log/apache2/access-test.log -a -o /var/www/index.html --real-time-html
```

**Comment by allinurl** [comment] 2017-01-20 18:19
You can certainly have goaccess on a dedicated server, is up to you how you feed access logs to it. If logs are on the same machine, then it should be a matter of pointing goaccess to those logs. Otherwise, you probably want to use something like rsyslog and have a centralized log server where goaccess can consume those logs. Or something as simple as sshfs may do it.

As far as processing logs incrementally, you will need to build/install goaccess with on-disk support (`--enable-tcb=btree`) and then you can make use of `--keep-db-files` and `--load-from-disk`. Please take a look at the [**examples for a how-to**](https://github.com/allinurl/goaccess#incremental-log-processing).

**Comment by Nitrosito** [comment] 2017-01-23 08:07
Yes, 7890 is opened. I can connect via telnet to it.
I use --ws-url too, and dont work.

Finally i think the solution will mount a dedicated server goaccess + rsyslog

**Comment by allinurl** [comment] 2017-01-24 19:58
@Nitrosito Did you build from development to test it out without using --ws-url?

**Comment by Nitrosito** [comment] 2017-01-26 10:41
I use the last build

**Comment by allinurl** [comment] 2017-01-26 13:04
Would you be able to post or send me an email with the URL where you have the report? So I can take a look what might be the issue (if any from the client side).

**Comment by Nitrosito** [comment] 2017-01-26 13:37
The server not Publish to ext

**Comment by allinurl** [comment] 2017-02-05 16:08
I was not able to reproduce this on my side. This appears to be an isolated issue, perhaps server configuration. especially if it worked on your local machine.

Closing this, feel free to reopen it if needed.

**Closed by allinurl** 2017-02-05 16:08 UTC
Labels: question, unable to replicate
