### ISSUE TITLE
Suddenly missing tons of data

### ISSUE THREAD

**Issue by MediaMaquina** [allinurl/goaccess#1987] opened 2020-12-28 01:08 UTC
I analyze a week worth of data and I only get a handful of hits. Bandwidth usage is 1.6Gib when it should be several terabytes. The time period is correct. The logs are ok. Nothing changed on the server. It used to work fine. I updated to latest version but it made no difference.

I'm lost, what can cause such thing?

**Comment by allinurl** [comment] 2020-12-28 02:30
Were you restoring and persisting data before?

**Comment by MediaMaquina** [comment] 2020-12-28 09:05
No I've never used those options. I didn't know they exist.
I noticed that when I run goaccess it finishes almost instantly when in the past it took a couple of seconds. Like it's deliberately ignoring log lines. No errors thought. Same log. Same config. I don't know how to debug it.

**Comment by allinurl** [comment] 2020-12-28 14:57
Can you please post a screenshot of what you are seeing? Also, can you try to feed goaccess with a smaller dataset or partial data and see if the results make sense. Thanks e.g. 

    tail -10000 access.log | goaccess -

**Comment by MediaMaquina** [comment] 2020-12-28 15:06
![Untitled](https://user-images.githubusercontent.com/8179611/103223329-44653380-4926-11eb-9d1d-9fa82ffd71c0.png)
I also sent you a week of logs by email subject is "Data seems missing".
I don't know if you do charge for the service i'm up for it. I really need this data, please contact me privately if you can.

**Comment by allinurl** [comment] 2020-12-28 16:43
Here's what I get in terms of tx amount from those logs you sent me.

If you check your logs, there are lot of requests (probably the majority) like the following and thus showing almost no TX. amount, so seems like your server did not send those requests, In CLF format, i.e. a '-' rather than a 0 when no bytes are sent.

    zcat -f fileserver2_apache.access.log* | less

yields to a bunch of:

    [18/Dec/2020:13:36:16 +0100] "GET /download.php?file=ULJS-00430.zip&id=108521&platform=psp&key=1966619921812 HTTP/1.0" 200 -

![2020-12-28-103808_661x233_scrot](https://user-images.githubusercontent.com/5005367/103229785-672d2300-48f9-11eb-87e6-6168d14ecdbc.png)

```
zcat -f fileserver2_apache.access.log* | wc -l
1090059
```

**Comment by MediaMaquina** [comment] 2020-12-28 16:59
Then the logs are wrong because those Tx. Amount should be in the order of Terabytes not MiB.
What could cause such a thing? i did migrate to SSL other than that i don't think i touched the servers.

**Comment by allinurl** [comment] 2020-12-28 17:29
You should try to enable more logging and see if you can pinpoint the issue, maybe bots are hitting your server? 

Editing /etc/apache2/apache2.conf

    LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %D %{Content-Type}o %{SSL_PROTOCOL}x %{SSL_CIPHER}x" vhost_combined_tls

and then ensure your sites are using that log format, e.g, /etc/apache2/sites-available/yoursite.conf

    CustomLog /var/log/apache2/access.log vhost_combined_tls

Then use this on your goaccess.conf

    log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D %M %K %k
    time-format %H:%M:%S
    date-format %d/%b/%Y

**Comment by MediaMaquina** [comment] 2020-12-28 19:16
Hi, ok i **believe** to have done what you said.
Logging successfully  started on a new file vhost_combined_tls.log, it looks like this:
`62.210.114.227:443 190.37.214.215 - - [28/Dec/2020:20:10:31 +0100] "GET /download.php?file=ULJM-05800-eng_v5.zip&id=80589&platform=psp&key=2266331425497 HTTP/1.0" 200 368 "https://dl2.cdromance.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko" 8016 application/zip - -`

Trying to goaccess it to a file. i get this:
```
==8907== FILE: vhost_combined_tls.log
==8907== Parsed 10 lines producing the following errors:
==8907==
==8907== Token '62.210.114.227:443' doesn't match specifier '%h'
```

I'm editing /etc/goaccess.conf, is it possible goaccess is not using that file? Because i commented out all log-format, time-format, and date-format hoping it would ask me to select them from the UI but it just gave me the exact same error from before.

**Comment by allinurl** [comment] 2020-12-28 19:22
Did you update your goaccess config file? Seems like it's still using the old one, you can find out which one you are using by running `goaccess --dcf` or you could try also:

    goaccess vhost_combined_tls.log --log-format='%v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D %M %K %k' --date-format=%d/%b/%Y --time-format=%T

**Comment by MediaMaquina** [comment] 2020-12-28 19:31
I seem to have 2  `goaccess --dcf ` worked.
![2](https://user-images.githubusercontent.com/8179611/103238436-fe6e9680-494a-11eb-8d68-ebe055690623.png)

But i think the problem persist. The log doesn't log how many bytes are transferred. I'm pretty sure it is transferring cos i see it on grafana at 800Mbps ~1 Gbps constantly.

**Comment by allinurl** [comment] 2020-12-28 22:01
Are you behind some sort of cache? are you using some service like cloudflare, etc that may be serving those files?

**Comment by allinurl** [comment] 2021-01-07 00:15
Per our conversation via email, it seems like the issue is related to the web server. Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2021-01-07 00:15 UTC
Labels: question
