### ISSUE TITLE
Docker : persisting parsed data 

### ISSUE THREAD

**Issue by Atrejoe** [allinurl/goaccess#1770] opened 2020-05-14 21:55 UTC
Using the ready-made Docker image, I'm failing to enable parsed data persistence.

command: `/srv/logs/access.log --real-time-html -o /srv/report/report.html --keep-db-files --load-from-disk --db-path /srv/data/all/`

error message: `/bin/goaccess: unrecognized option: keep-db-files`

Or in full `docker-compose`, demonstrating shared volumes:

```docker-compose
version: "3"
services:
  goaccess_all:
    image: allinurl/goaccess:latest
    command: /srv/logs/access.log --real-time-html -o /srv/report/report.html --keep-db-files --load-from-disk --db-path /srv/data/all/
    volumes:
      - './data:/srv/data'          #Path to Geoip databases
      - '../NGinx/log:/srv/logs:ro' #Path where NGinx stores logfiles
      - './html:/srv/report'        #Path to output report
      - './conf:/etc/goaccess'      #Path to config
    restart: always
```

Is this supported, or am I overlooking something in the docs?

>Note:
>I'm trying to this because the reports contain a limited number of days. The logs I'm parsing however contain multiple months of data. It appears that goaccess does not parse all data in the log files.

**Comment by allinurl** [comment] 2020-05-14 22:01
v1.4 updated the way it persists data. Since Docker builds from upstream, the recently pushed changes got rid of  `--keep-db-files` `--load-from-disk`. Please try instead `--persist` and `--restore`. In addition, it adds `--keep-last=<num_of_days>` and addresses #334.

I'm still working on updating the docs for the upcoming release, which is around the corner.

Let me know how it goes. Thanks

**Comment by Atrejoe** [comment] 2020-05-14 22:03
Wow, that's a fast response.
How can I specify where to store the permanent data?

**Comment by allinurl** [comment] 2020-05-14 22:08
Still `--db-path` or /tmp by default. 

What do you mean with look further back in the logs? You should be able to feed goaccess as much data as you need, though, it displays top data (different than time series).

**Comment by Atrejoe** [comment] 2020-05-14 22:14
with `/srv/logs/access.log --real-time-html -o /srv/report/report.html --persist --restore --db-path /srv/data/all/`, I get: `/bin/goaccess: unrecognized option: persist`

when I execute `goaccess --version` I see this is 1.3, when I do docker-compose pull, I do not get a new image.

Regarding the period of data being shown:
![image](https://user-images.githubusercontent.com/585091/81990863-4b159380-9640-11ea-95c4-d6da7870190d.png)

**Comment by Atrejoe** [comment] 2020-05-14 22:24
Looks like 1.3 does not contain the option to persist, I guess I may need to build the latest from source.

**Comment by allinurl** [comment] 2020-05-14 22:35
My bad, I didn't trigger a build in Docker thus still was showing v1.3. Please try to build again. 

You can use `--max-items=<num_entries_to_show>` by default is set to 365 to a static report. A fixed <= 50 for a real time report.

**Comment by Atrejoe** [comment] 2020-05-14 23:04
Again: fast to release the new docker image!
It appears to work too (at least I see database files appear and it doesn't crash).
I still don't get it to look back (or report back) a longer period though.

I also see the 1.4 generated report does not show the displayed period:
![image](https://user-images.githubusercontent.com/585091/81994182-8f586200-9647-11ea-9f6c-837b0ce35cfe.png)

Is there a changelog between 1.3 and 1.4, so I know where to look at? Maybe I need to update  my [goaccess.conf](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf) file too.

**Comment by allinurl** [comment] 2020-05-15 00:50
> I still don't get it to look back (or report back) a longer period though.

Are you outputting a real-time report?

> I also see the 1.4 generated report does not show the displayed period:

Are you able to reproduce this [**from source**](https://github.com/allinurl/goaccess#build-from-github-development) (without docker) and could you please post the config file you are using?

> Is there a changelog between 1.3 and 1.4, so I know where to look at? Maybe I need to update. my goaccess.conf file too.

I'm still working on the changelog and docs for next week release. Stay tuned :)

**Comment by Atrejoe** [comment] 2020-05-15 19:44
> Are you outputting a real-time report?

Yes, when I make it non-real time, I get a bit more. Would it be possible to display all, or a configurable period?
I'm not sure what real-time means though, if this is false, does the Docker containers still parse the log files from time to time?

>Are you able to reproduce this from source (without docker) and could you please post the config file you are using?

Yes, I think with docker-compose using `build: .` after doing a git clone from `master`, I have the same result. At first I thought it my be a miniature font, but they are actually hyphens.

![image](https://user-images.githubusercontent.com/585091/82089992-fbdd6a80-96f4-11ea-84a5-96f4a601d5f8.png)

docker-compose (see `build: .`)
```
version: "3"
services:
  goaccess_all:
    build: .
    command: /srv/logs/access.log -o /srv/report/report_built_from_source.html
    volumes:
      - '../goaccess/data:/srv/data'          #Path to Geoip databases
      - '../NGinx/log:/srv/logs:ro'           #Path where NGinx stores logfiles
      - '../goaccess/html:/srv/report'        #Path to output report
      - '../goaccess/conf:/etc/goaccess'      #Path to config
    restart: always
```
my config (without comments and listing of static files). I just removed real-time=true.
```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format VCOMBINED
config-dialog false
hl-header true
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false
agent-list true
with-output-resolver true
exclude-ip 127.0.0.1
exclude-ip 192.168.0.1-192.168.0.100
http-method yes
http-protocol yes
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files true
date-spec hr
double-decode false
ignore-crawlers false
crawlers-only false
real-os true
geoip-database /srv/data/GeoLite2-City.mmdb
```

Regarding the changelog and docs, cool, how to you gather the changes?

**Comment by allinurl** [comment] 2020-05-16 04:08
I updated the [**README.md**](https://github.com/allinurl/goaccess#docker).

Here's how I got it to run in real-time:

    cat access.log | docker run -p 7890:7890 --rm -i -e LANG=$LANG allinurl/goaccess -a -o html --log-format COMBINED --real-time-html - > report.html

> Regarding the changelog and docs, cool, how to you gather the changes?

I do have a script that goes over the commit messages based on certain patterns. Though, it requires some manual updates.

Let me know how it goes.

**Comment by allinurl** [comment] 2021-02-09 01:35
Closing this. Please try the latest version as there have been multiple changes that may address this. Feel free to reopen it if needed.

**Closed by allinurl** 2021-02-09 01:35 UTC
Labels: docker
