### ISSUE TITLE
Correct command line for goaccess to work with pipe and multiple log files?

### ISSUE THREAD

**Issue by peidaqi** [allinurl/goaccess#1269] opened 2018-10-15 18:12 UTC
The example given by the author in #840 , if used with the sample goaccess.conf from repo doesn't really work for me.
To fix the 'No date format was found on your conf file.' error when using the command with pipe and multiple files, one can create a file like:
```
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```
And use the command line:
> {cat access.log; cat access.log.1; zcat -f /var/log/apache2/access.log.*.gz} | goaccess -p ~/.goaccessrc

This aggregates all the logs from a standard apache2 configuration.

Tested on Ubuntu18.04 + zsh. If this works for everyone, I hope it can be included in the manual (also pointing out you need to explicitly specify the conf file when using with pipe) because it is the most common task people would perform with this software, and the examples from the current manual doesn't work for me at all. - this can save millions of people lots of googling time.

**Comment by allinurl** [comment] 2018-10-16 00:03
Thanks for posting this. 

Could you please post a concrete example of what's not working for you so I can try to reproduce this from my side? also the exact version of goaccess that you are running. Thanks.

**Comment by peidaqi** [comment] 2018-10-16 13:32
I'm not sure if it's related to my environment, but none of the examples in - https://goaccess.io/man, section 'MULTIPLE LOG FILES' works.

My goaccess was cloned from the repo and built from scratch.

**Comment by allinurl** [comment] 2018-10-17 14:08
Can I ask what's the full command that you using? Thanks.

**Comment by peidaqi** [comment] 2018-10-18 19:04
I tried all the commands in section "Multiple Log Files" and none of them worked.
Only one worked is as I posted in the OP.

**Comment by sedevops** [comment] 2018-10-24 06:31
Same issue. `Multiple log files` doesn't work as expected

**Comment by favoyang** [comment] 2019-08-10 06:10
Env
- ubuntu distribution v0.9.4.
- nginx default log format.
- daily rotation (.log, .log.1, .log.2.gz, ...).
- bash 4.3.48(1)

None of below works
```
goaccess access.log access.log.1
goaccess -f access.log access.log.1
zcat access.log.*.gz | goaccess access.log - 
zcat access.log.*.gz | goaccess -f access.log - 
```

what works
```
cat access.log access.log.1 | goaccess
zcat access.log.*.gz | goaccess
```

Then I realized I can use `zcat -f` for both compressed and uncompressed input.

Finally,
```
zcat -f access.log access.log.* | goaccess
or 
zcat -f access.lo* | goaccess
```

**Comment by allinurl** [comment] 2019-08-13 14:33
@favoyang The ones that didn't work for you it's due to the version you are running, please use the latest version of goaccess v1.3.

**Comment by favoyang** [comment] 2019-08-14 03:24
You're right. The 1.3 fix this. 

```
zcat access.log.*.gz | goaccess access.log - 
```

Let's close this issue then.

**Comment by allinurl** [comment] 2019-08-20 15:48
Closing this as it has been verified that v1.3 fixes this. Feel free to reopen it if needed.

**Closed by allinurl** 2019-08-20 15:48 UTC
Labels: documentation, log/date/time format
