### ISSUE TITLE
localStorage errors

### ISSUE THREAD

**Issue by hdatma** [allinurl/goaccess#511] opened 2016-09-05 13:00 UTC
In private browsing mode, all major browsers fail to render the statistics. 
There is an explanation and possible solutions at the following page:
http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st#23453866

**Comment by allinurl** [comment] 2016-09-05 17:15
I just tested [**this**](http://rt.goaccess.io/?gh) on FF and Chrome, both in incognito/private mode and they work fine. What errors are you getting? and what browser version are you using?

**Comment by hdatma** [comment] 2016-09-05 17:38
The errors show up when reading the stats file from the local file system.

**Comment by allinurl** [comment] 2016-09-05 21:14
Have you tried building from [development](https://github.com/allinurl/goaccess#build-from-github-development)? This was addressed on this [commit](https://github.com/allinurl/goaccess/commit/2a35f31a45be83c1a1f501e030bd510d5800268e). Please let me know if that fixes the issue for you.

**Comment by allinurl** [comment] 2016-09-08 02:09
Closing this given my previous post. Feel free to reopen it if needed.

**Closed by allinurl** 2016-09-08 02:09 UTC
Labels: question

**Comment by hdatma** [comment] 2016-09-08 11:10
Latest from dev returns errors for latest FF-ESR:

TypeError: localStorage is null
hasLocalStorage() stats:59
<anonymous> stats:82
<anonymous> stats:1
insertScript() supercookie.js:32
<anonymous> supercookie.js:146
load()  sandbox.js:66
importScripts()  sandbox.js:326
WorkerSandbox() sandbox.js:287
constructor() heritage.js:146
initialize() worker-child.js:52
constructor() heritage.js:146
createWorker() page-mod.js:156
onContent() page-mod.js:189
onContentWindow() page-mod.js:121

**Comment by allinurl** [comment] 2016-09-08 23:42
I'm not able to reproduce this. Tested on FF 48.0.2. Have you tried with a new version of FF?
