### ISSUE TITLE
How to parse multiple logs for multipe hosts

### ISSUE THREAD

**Issue by crebuh** [allinurl/goaccess#1148] opened 2018-06-15 08:26 UTC
Hey Guys,

we are running a couple of sites on one of our servers. Each of them have one locations for the access logs. I was wondering if it is possible to use a command like this to combine all log files to one output.

> goaccess --log-format=COMBINED /sites/**/logs/access.log

Inside /sites/ there are a couple of folders with another subfolder and the mentioned log files. What would be the best attempt to combine all of those and display also the hostname inside the goaccess dashboad?

Here is an example of one of those access logs. I added the hostname at the beginng to identify the host easier.

> www.domain.com 79.234.48.148 - - [15/Jun/2018:10:17:10 +0200] "GET /dsgvo-und-webseiten/ HTTP/2.0" 200 23023 "https://www.google.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36" "4.04"

**Comment by allinurl** [comment] 2018-06-15 14:12
I'd try this, it should work:

```
find /sites/ -type f -name "*.log" -exec cat {} + | goaccess --log-format='%v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%L"' --date-format=%d/%b/%Y --time-format=%T
```

assumes the following structure

```
sites/
├── server1/
│   └── access.log
├── server2/
│   └── access.log
├── server3/
│   └── access.log
└── server4/
    └── access.log
```

**Comment by allinurl** [comment] 2018-06-15 14:30
Correction:

    find /sites/ -type f -name "*.log" -exec cat {} + | goaccess --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%T"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment] 2018-06-20 12:06
Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2018-06-20 12:06 UTC
Labels: log-processing, question

**Comment by crebuh** [comment] 2018-08-01 07:54
@allinurl 

additional question here. is it possible to add the hostname also the other sections of the report like requested files or not found urls. so it will be easier to identify the host where does 404 urls occur. It would be great to see something like:

> 126 (63.64%) | 0 (0.00%) | 14.04 MiB (92.90%) | 0.00 us | 0.00 us | 0.00 us | GET | HTTP/1.1 | mydomain.com/wp-login.php

instead of just wp-login.php at the end. So I have no clue on which host the 404 occured.

**Comment by allinurl** [comment] 2018-08-01 13:55
Yes, it is possible. Please take a look at the https://goaccess.io/man#examples page (virtualhost section), it should let you do what you are looking for.

**Comment by crebuh** [comment] 2018-08-01 14:16
@allinurl 

my command is already pretty complicated

> find /sites/ -type f -name "access.log" -exec cat {} + | goaccess - --ignore-crawlers --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%T"' --date-format=%d/%b/%Y --time-format=%T -o /var/www/html/report.html

and I guess I have to incorporate this part somehow

> awk '$8=$1$8'

but I'm not sure how or where

**Comment by allinurl** [comment] 2018-08-01 14:43
This should do it:

    find /sites/ -type f -name "*.log" -exec cat {} + | awk '$8=$1$8' | goaccess --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%T"' --date-format=%d/%b/%Y --time-format=%T -

**Comment by allinurl** [comment] 2018-08-08 15:28
Please post the structure of your logs and attach a file with some sample lines so I can try to replicate the exact same thing, otherwise it's difficult to tell what might be the issue as I don't have the same environment. Thanks.

**Comment by crebuh** [comment] 2018-08-16 13:02
@allinurl 

The log file format is:

``
log_format custom_format '$server_name $remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" "$gzip_ratio"';
``

Here is an excerpt of 20 lines of the access.log

``
www.domain.co 172.104.149.68 - - [16/Aug/2018:14:37:33 +0200] "HEAD / HTTP/1.1" 200 0 "-" "Monit/5.16" "-"
www.domain.co 46.229.168.69 - - [16/Aug/2018:14:39:26 +0200] "GET /tag/javascript/ HTTP/1.1" 200 113002 "-" "Mozilla/5.0 (compatible; SemrushBot/2~bl; +http://www.semrush.com/bot.html)" "5.84"
www.domain.co 172.104.149.68 - - [16/Aug/2018:14:39:34 +0200] "HEAD / HTTP/1.1" 200 0 "-" "Monit/5.16" "-"
www.domain.co 119.226.211.80 - - [16/Aug/2018:14:40:10 +0200] "GET /angular-2-ionic-2-what-you-have-to-know/ HTTP/1.1" 200 118523 "https://www.google.co.in/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "5.69"
www.domain.co 119.226.211.80 - - [16/Aug/2018:14:40:11 +0200] "GET /wp-includes/js/jquery/jquery.js?ver=1.12.4 HTTP/1.1" 200 34016 "https://www.domain.co/angular-2-ionic-2-what-you-have-to-know/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "2.86"
www.domain.co 119.226.211.80 - - [16/Aug/2018:14:40:12 +0200] "GET /wp-includes/js/wp-emoji-release.min.js?ver=4.9.8 HTTP/1.1" 200 4434 "https://www.domain.co/angular-2-ionic-2-what-you-have-to-know/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "2.72"
www.domain.co 119.226.211.80 - - [16/Aug/2018:14:40:13 +0200] "GET /wp-content/cache/autoptimize/js/autoptimize_e460717e66d6116df564c88b0505719a.js HTTP/1.1" 200 167910 "https://www.domain.co/angular-2-ionic-2-what-you-have-to-know/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "3.54"
www.domain.co 142.44.232.99 - - [16/Aug/2018:14:40:19 +0200] "GET / HTTP/1.1" 200 124041 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "6.09"
www.domain.co 223.72.99.160 - - [16/Aug/2018:14:40:37 +0200] "GET /13-useful-modules-for-any-nodejs-restful-api-boilerplate/ HTTP/2.0" 200 118331 "https://www.google.com.hk/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "5.69"
www.domain.co 223.72.99.160 - - [16/Aug/2018:14:40:38 +0200] "GET /wp-includes/js/jquery/jquery.js?ver=1.12.4 HTTP/2.0" 200 34206 "https://www.domain.co/13-useful-modules-for-any-nodejs-restful-api-boilerplate/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "2.86"
www.domain.co 223.72.99.160 - - [16/Aug/2018:14:40:38 +0200] "GET /wp-includes/js/wp-emoji-release.min.js?ver=4.9.8 HTTP/2.0" 200 4624 "https://www.domain.co/13-useful-modules-for-any-nodejs-restful-api-boilerplate/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "2.72"
www.domain.co 223.72.99.160 - - [16/Aug/2018:14:40:41 +0200] "GET /wp-content/cache/autoptimize/js/autoptimize_e460717e66d6116df564c88b0505719a.js HTTP/2.0" 200 168053 "https://www.domain.co/13-useful-modules-for-any-nodejs-restful-api-boilerplate/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "3.54"
www.domain.co 89.143.60.153 - - [16/Aug/2018:14:41:32 +0200] "GET /wp-login.php HTTP/1.1" 404 191485 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1" "-"
www.domain.co 89.143.60.153 - - [16/Aug/2018:14:41:33 +0200] "GET / HTTP/1.1" 200 755397 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1" "-"
www.domain.co 172.104.149.68 - - [16/Aug/2018:14:41:37 +0200] "HEAD / HTTP/1.1" 200 0 "-" "Monit/5.16" "-"
www.domain.co 46.229.168.82 - - [16/Aug/2018:14:41:44 +0200] "GET /author/lydia/page/2/ HTTP/1.1" 301 5 "-" "Mozilla/5.0 (compatible; SemrushBot/2~bl; +http://www.semrush.com/bot.html)" "-"
www.domain.co 46.229.168.77 - - [16/Aug/2018:14:41:49 +0200] "GET / HTTP/1.1" 200 124041 "-" "Mozilla/5.0 (compatible; SemrushBot/2~bl; +http://www.semrush.com/bot.html)" "6.09"
www.domain.co 163.44.206.175 - - [16/Aug/2018:14:42:27 +0200] "POST /xmlrpc.php HTTP/1.1" 200 441 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.1) Gecko/2008070208 Firefox/3.0.1" "-"
www.domain.co 163.44.206.175 - - [16/Aug/2018:14:42:31 +0200] "POST /xmlrpc.php HTTP/1.1" 200 441 "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.1) Gecko/2008070208 Firefox/3.0.1" "-"
www.domain.co 172.104.149.68 - - [16/Aug/2018:14:43:40 +0200] "HEAD / HTTP/1.1" 200 0 "-" "Monit/5.16" "-"
``

**Comment by crebuh** [comment] 2018-08-22 06:14
@allinurl 

does it help you?

**Comment by allinurl** [comment] 2018-08-23 00:37
Sorry for my late reply. This should work:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by crebuh** [comment] 2018-08-28 07:50
@allinurl 

hmm now all time related columns disappeared and the unique visitors table is still empty. should I provide additional log examples?

**Comment by allinurl** [comment] 2018-08-28 11:48
Yes, please attach a file with a substantial number request where I can reproduce this from my side. Also, please post the exact command you are using and config options. Thanks.

**Comment by crebuh** [comment] 2018-08-28 12:10
@allinurl 

sure here are the commands:

``
#!/usr/bin/env bash
find /sites/ -type f -name "access.log" -exec cat {} + | awk '$8=$1$8' | goaccess - --ignore-crawlers --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%T"' --date-format=%d/%b/%Y --time-format=%T -o /var/www/html/report.html
# find /sites/ -type f -name "access.log" -exec cat {} + | awk '$8=$1$8' | goaccess - --ignore-crawlers --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T -o /var/www/html/report.html
``

As said the first one workes the second did not.

You can download log files from two different hosts [here](https://www.dropbox.com/s/lcls10ydnm5qy9w/logs.tar.gz?dl=0)

**Comment by allinurl** [comment] 2018-09-05 20:28
I was checking this and I see you have two different `log-format`s in your previous post. That's probably the reason.

**Comment by edvegas** [comment] 2020-05-22 12:19
may be useful for someone

Solution that worked for me for real time html pages (dynamic page update):
`find /sites/ -type f -name "*.log*" | xargs goaccess \
--log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%T"' \
--date-format=%d/%b/%Y --time-format=%T \
--real-time-html`

**Comment by edvegas** [comment] 2020-05-22 12:49
dynamic update + all history (archived files)
find and save recent files lists to variable:
`non_archived_files=$(find /sites/ -type f -name "access.log" -o -name "access.log.1")`

attach archives also and execute
`find /var/log/apache2/total/ -type f -name "access.log.*.gz" | xargs zcat | goaccess ${non_archived_files}  --log-format COMBINED --date-format %d/%b/%Y --time-format %T`
