### ISSUE TITLE
Total Requests != Valid Requests + Failed Requests

### ISSUE THREAD

**Issue by vsayyagari** [allinurl/goaccess#1952] opened 2020-11-02 03:31 UTC
I have started using goaccess recently (v1.4). I don't understand why the Total Requests are not the same as sum of Valid Requests and Failed Requests. The Total Requests match the count in the log file.  Clearly, my lack of undersatnding. Please help. 
Thanks,
vs

This is how I am calling goaccess:
`
goaccess jetty/app-base/logs/*.request.log -o /var/www/html/report.html 
	--geoip-database geolitedb/GeoLite2-City_20201006/GeoLite2-City.mmdb 
	--real-time-html 
	--ws-url=localhost 
`

![goaccess_web_ui](https://user-images.githubusercontent.com/7355770/97827139-45f0e300-1c78-11eb-945e-a5d363621d4c.png)

**Comment by allinurl** [comment] 2020-11-02 03:41
Did you at some point persist or restore data using `--persist` or `--restore`?

**Comment by thomas-mc-work** [comment] 2020-12-15 19:25
What's the difference then?

**Comment by allinurl** [comment] 2020-12-15 19:31
@thomas-mc-work If the data was persisted and then you parse again the same log while restoring the persisted data, the total requests increases as it reads each line again. Though,  valid/failed requests won't as it considers those lines being duplicated.

Also, make sure to upgrade to v1.4.3 as there was a glitch on the restoring code prior to v1.4.3.

Closing this, feel free to reopen it if needed.

**Closed by allinurl** 2020-12-15 19:31 UTC
Labels: log-processing

**Comment by MoritzLost** [comment] 2022-01-07 13:54
@allinurl Is this still the expected behaviour?

Some background: We're running goaccess multiple times a day with the `--persist` and `--restore` arguments to update the static HTML file generated by it. nginx logs are rotated daily. Does that mean that each time goaccess runs, it will increment the 'Total Requests' by the number of ALL lines in the nginx log for that day, regardless of whether those lines have been processed already in the previous run? I assumed the restore/persist parameters kept track of which lines it had processed already. Doesn't that make the Total Requests metric completely useless when using persist/restore?

**Comment by allinurl** [comment] 2022-01-08 03:45
It does keep track of those processed lines. Do you know if you are truncating the log upon rotation? unless `copytruncate` is used in logrotate, it just renames the log. If it just moves the file and is within the file system boundaries, then it should just perform a metadata change, so it should preserve the inode number, which should work as expected :)

BTW, do you have some numbers of what you are seeing on your end? Thanks

**Comment by MoritzLost** [comment] 2022-01-10 11:00
@allinurl Thanks for the reply! We're using logrotate with a daily rotation, the logs aren't truncated. Anyway, we're only feeding the current log into goaccess, so it won't see the rotated logs, only the current log for that day. Here's our cronjob script:

```bash
#!/bin/bash
BASE="/path/to/output/dir"
GOACCESS_DB="${BASE}/goaccess-db/"
mkdir -p $GOACCESS_DB
cat /var/log/nginx/access.log | grep -v -f "${BASE}/exclude_list.txt" | goaccess - -o "${BASE}/index.html" --log-format=COMBINED --ignore-crawlers --anonymize-ip --all-static-files --static-file=.webp --static-file=.map --static-file=.json --db-path $GOACCESS_DB --restore --persist
```

This runs once an hour. So in this case, the lines in the daily log aren't counted repeatedly?

I had a look at the numbers – the total requests count seemed a bit high, but looks like it matches the number of lines in the latest nginx log. Total requests in january are ~170k so far, and the daily logs have about 20k lines each (some of those are excluded by the exclude list, which has some internal paths and IP addresses). So I guess factoring in all bot traffic and other everything the numbers look legit. Thanks for the explanation!
