### ISSUE TITLE
counters updating but the date is stalled

### ISSUE THREAD

**Issue by jazzl0ver** [allinurl/goaccess#830] opened 2017-07-05 16:53 UTC
Hello.

The command line I use to run goaccess:

    /usr/bin/goaccess - --port=7890 -o /var/www/html/report.html --keep-db-files --load-from-disk --db-path=/var/lib/goaccess/ --compression bz2 --real-time-html < <(/usr/bin/socat -t3 -u UNIX-RECV:/tmp/haproxy.sock -) >/dev/null

For some reason the date period is stalled with "21/JUN/2017-30/JUN/2017", however the counters are still updating.

Addon: the only counters that get updated are total, valid and failed requests on top of the page

Any ideas what to check?

**Comment by allinurl** [comment] 2017-07-05 17:28
Does refreshing/reloading the page on your browser work? Also, do you see the expected dates within the visitors panel? Thanks.

**Comment by jazzl0ver** [comment] 2017-07-06 09:08
1. No, reloading the page as well as restarting goaccess does not help
2. No, the last date everywhere is 30/Jun/2017

**Comment by allinurl** [comment] 2017-07-06 14:27
Looks like the data source could the issue. Can you please verify that the input log given to goaccess has the latest dates? For instance, use tail -F  to see if `< <(/usr/bin/socat -t3 -u UNIX-RECV:/tmp/haproxy.sock -)` has those dates. Thanks.

**Comment by allinurl** [comment] 2017-07-06 14:30
Please also make sure you have a valid log/date/time format that matches the source log.

**Comment by jazzl0ver** [comment] 2017-07-06 15:15
I've just run socat without goaccess and here is its output:
```
# /usr/bin/socat -t3 -u UNIX-RECV:/tmp/haproxy.sock -  | head -1
Jul  6 15:11:03 80.70.x.x:18415 [06/Jul/2017:15:11:03.202] ...
```
```
# grep format /etc/goaccess.conf | grep -v "^#"
time-format %H:%M:%S
date-format %d/%b/%Y
log_format %^ %^ %^ %^ [%d:%t.%^] %^ %^ %^/%^/%^/%^/%L %^ %^ %^ "%r" %s {%^|%^|%^|%u} %^ %^=%b %^ %h:%^ %^ %^ %^
```

**Comment by allinurl** [comment] 2017-07-06 15:35
Got it. Can I ask you to run a test by getting rid of `--load-from-disk` and see if that's where the issue is. If that still doesn't work, and if you don't mind loosing the current stored data-set, please try without `--keep-db-files`. Thanks.

**Comment by jazzl0ver** [comment] 2017-07-06 15:57
Without "--load-from-disk":
![image](https://user-images.githubusercontent.com/2444175/27920304-cbec1650-627c-11e7-8e4c-1c984d3a88ab.png)

Should I try without "--keep-db-files" only or without "--keep-db-files" AND without "--load-from-disk"?

**Comment by allinurl** [comment] 2017-07-06 16:03
Before doing that and since you got a bunch of failed requests, can you please post a few lines from your log so I can test the log-format you posted above. Thanks.

**Comment by jazzl0ver** [comment] 2017-07-06 16:19
```
Jul  6 16:14:05 50.79.1.1:64163 [06/Jul/2017:16:14:00.748] lb-useast~ frontend_app1_backend/sp-useast-001 4669/0/1/11/4681 --VN 83/74/0/1/0 0/0 "POST /app1/navmessages/api/alerts HTTP/1.1" 200 {||142|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59} ireq_size=2829 resp_size=168 172.30.1.57:443 54.84.1.1:443 ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 B6:A3_39:BB_C8_D5:B2
Jul  6 16:14:05 75.147.1.1:54888 [06/Jul/2017:16:14:05.283] lb-useast~ frontend_app1_backend/sp-useast-001 141/0/2/10/153 --VN 93/86/1/2/0 0/0 "POST /app1/navmessages/api/alerts HTTP/1.1" 200 {||162|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59} ireq_size=2106 resp_size=168 172.30.1.57:443 54.84.1.1:443 ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 51:68_39:BB_CD_A8:8B
Jul  6 16:14:05 66.87.1.1:16078 [06/Jul/2017:16:14:00.306] lb-useast~ frontend_ls_backend/sp-useast-006 5139/0/1/22/5162 --NI 93/86/0/1/0 0/0 "POST /ls/apiLocation/location HTTP/1.1" 200 {||386|Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-N910P Build/MMB29M)} ireq_size=639 resp_size=157 172.30.1.57:443 54.172.1.1:443 ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 A8:39:C8_5A:8B
```

**Comment by allinurl** [comment] 2017-07-06 16:25
Please try this:

```
log-format %^[%d:%t.%^] %^ %^ %^/%^/%^/%^/%L %^"%r" %s {%^|%^|%^|%u} %^ %^=%b %^ %h:%^
date-format %d/%b/%Y
time-format %T
```

**Comment by jazzl0ver** [comment] 2017-07-06 16:30
it works. adding "--load-from-disk" does not load the past data

**Comment by allinurl** [comment] 2017-07-06 16:32
Good. Now try to see if everything else is working fine and let me know. Note that if you didn't use `--keep-db-files` on a previous command, then all previous data is deleted upon exiting goaccess.

**Comment by jazzl0ver** [comment] 2017-07-06 16:34
OK. I didn't remove ```--keep-db-files``` from the command line

**Comment by jazzl0ver** [comment] 2017-07-07 09:10
It works so far, thank you! Any chances to get data back from the database for the previous period?

**Comment by allinurl** [comment] 2017-07-07 11:29
You will need to parse the log again. I think the issue was after removing --load-from-disk and passing a new data source. So when you exited the program, it kept the new data but since the old data was not loaded, it got discarded. Sorry about the confusion on that.

**Comment by allinurl** [comment] 2017-07-07 13:48
Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2017-07-07 13:48 UTC
