### ISSUE TITLE
Access log issues and cPanel

### ISSUE THREAD

**Issue by willhb86** [allinurl/goaccess#661] opened 2017-02-15 16:27 UTC
I've installed goaccess but I'm running to an issue. on my VPS linux Centos 6

Using command "goaccess -f /var/log/httpd/access_log" (access.log doesn't exist) I get the the log format configuration screen, no matter what I select I get this error "Format Errors - Verify your log/date/time format" and when I look at my log file using VI its blank.

However, in my /usr/local/apache/logs there is a access_log and the structure is.

    127.0.0.1 - - [31/Dec/2015:16:36:18 -0600] "GET /index.html HTTP/1.1" 200 111

But the issue is it only shows access to WHM. Any ideas?

**Comment by allinurl** [comment] 2017-02-15 17:11
Not sure I follow your question, is your access log located under `/usr/local/apache/logs` or `/var/log/httpd/`? It looks like your log format is a COMMON log, just make sure to select that from the config dialog.

**Comment by willhb86** [comment] 2017-02-15 19:11
I've figured most of it out. I'm having issues with data being displayed tho. Take a look, http://velocityrestorations.com/goaccess/report.html

Also after I execute the command for real time results it generates the page, but in ssh it shows "Parsing ... [6,094] [0/s] and then ssh wont work. I have to reset the ssh software.

**Comment by willhb86** [comment] 2017-02-15 19:12
Under centos with cpanel installed logs are stored in /usr/local/apache/domlogs/

**Comment by allinurl** [comment] 2017-02-15 19:40
Are you adding some additional scripts to the report? I see some `CloudFlare`stuff that won't let me open it.

**Comment by willhb86** [comment] 2017-02-15 19:51
Try this, http://132.148.19.195/~velocityresto/goaccess/report.html

**Comment by allinurl** [comment] 2017-02-15 20:10
Looks like the issue is on `--ws-url`. You only need to specify the host/IP of the machine where goaccess is running, nothing else (**no path, no url scheme**). For instance,

`--ws-url=velocityrestorations.com` or `--ws-url=132.148.19.195`

If you want to ignore `"Parsing ... [6,094] [0/s]`, please use `--no-progress`.

**Comment by willhb86** [comment] 2017-02-15 22:19
Thanks, one last question. What is the update duration? is there a way for this to update every 60 seconds?

**Comment by allinurl** [comment] 2017-02-16 01:03
It will update every second as long as new data is appended to the access log. There's no option right now to set how often you want the report to be updated. Any reason why you want the update every 60secs?

**Comment by willhb86** [comment] 2017-02-16 20:35
Having this issue, can't figure it out. It updates like it should then a few mins in it stops. I have to process the command again to get it to start, but it just stops after a few mins. Any ideas?

**Comment by allinurl** [comment] 2017-02-16 23:43
Can you please post the content of your browser console (Ctrl+Shift+j in Chrome)? Thanks

**Comment by allinurl** [comment] 2017-02-20 02:10
Were you able to figure it out. Please take a look at my last comment if you haven't. Thanks.

**Comment by allinurl** [comment] 2017-02-21 13:07
Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2017-02-21 13:07 UTC
Labels: question
