### ISSUE TITLE
parsing stopps at first empty logfiles

### ISSUE THREAD

**Issue by gerhard-tinned** [allinurl/goaccess#1683] opened 2020-02-26 19:24 UTC
I am using goaccess version 1.2 which I knowis not the latest version. Still I have seen no issue about this, not even a closed one. I was wondering if I do something wrong. 

I use goaccess to generate a summary of all current logs of all my webhosts like this. 

```
goaccess -f /home/webhost1/log/*access*.log /home/webhost2/log/*access*.log -o /path/to/report.html --date-spec=hr --hour-spec=min
```

I noticed after log rotate was triggered (and some logs stay empty for a while) that the processing stopped at the first empty log file processed. The output shows the empty logfile name - nothing more, no error. 

When I use `find` with the `-not -emty` parameter to filter out the empt files, it works as expected. If there are no empty log files passed via the `-f` arhgument, it works as expected. 

I know version 1.2 is not the latest. I was wondering if this still exists in version 1.3.

**Comment by allinurl** [comment] 2020-02-28 00:29
Interesting, I can't tell you if this is an issue on v1.3 until I can run some sort of test. Are you able to reproduce this without the auto  rotation? Thanks

**Comment by gerhard-tinned** [comment] 2020-02-28 13:32
Short Answer, I can trigger that behaviour.

Long one, ... My Setup looks like that. I have a very simple shell script to generate the goaccess html reports. The procedure looks like that:

1.) I go through all the webhosts and define the path to the log files like that: 
   "/path/to/$WEBHOST/logs/*.access.*log-*"
   That pattern with "log-*" at the end only matches already rotated logs. 
2.) I use that pattern to start goaccess with "-o /.../hist.html", --db-path, --keep-db-files and --load-from-disk
    From my understanding, this will read the db into goaccess, load the log files, and keeps the db files. At this point I figured out that you have done a GREAT job identifying already loaded files. That reduces the complexity in my simple shell script. 
3.) I get the file path to the current log files (the not jet rotated ones like that:
     "/path/to/$WEBHOST/logs/*.access.*log"
    This matches only the current unrotated log. As this log files is changing on every request, I cannot load it into the same database as data would be loaded multiple times. 
4.) So I generate a separate report for them using the "-o /.../index.html", --date-spec=hr and --hour-spec=min
   I do not keep or load the db as it would only show garbage. I use --date-spec=hr and --hour-spec=min to see more details for the current logfile report. 

The Problem was noticed when I created the report for the current logfile using 
```
goaccess -f /../*access.*.log /../*access.*.log -o /../index.html --log-format=COMBINED --date-spec=hr --hour-spec=min
```
One of the files referenced in the -f parameter was an empty file (filesize 0 byte). goaccess starts,  prints the log file name to the console and ends without a real error message. But what I noticed was that the report file (/../index.html) was not even created. I investigated and found that the empty file triggered the termination of the processing. 

Current workaround:

When I use find to interpret the path/file pattern and remove empty files, the report file is created and works as expected. 

```
find /../*access*.log -not -empty
```

I could test this quiet extensive as it happened on every run (have a webhost with nearly no access at all (reason does not matter I guess). 

I guess with that details it should be easy to reproduce if the issue still exists in version 1.3, right?

**Comment by gerhard-tinned** [comment] 2020-03-02 12:21
Reproducable with following test procedure using goaccess 1.2:
1. placed two log files into a directory. both contain some apache access log lines. 
2. Run goaccess to verify correct behaviour -> OK
    ```
    goaccess -f *.log -o working.html  --log-format=COMBINED --date-spec=hr --hour-spec=min
    ```
3. create an empty file matching the input file pattern
    ```
    touch some.webserver.log
    ```
4. Run the goaccess command again with different out filename.
    ```
    goaccess -f *.log -o failed.html  --log-format=COMBINED --date-spec=hr --hour-spec=min
    ```

The result is one generated file called "working.html" but no file named "failed.html" is created.

This was the test using version 1.2. As Centos 7 still uses 1.2, I am still using veersion 1.2 of GoAccess.

**Comment by allinurl** [comment] 2020-03-02 15:05
Thanks for sharing those details, let me look into this and I'll post back.

**Comment by ericloyd** [comment] 2024-01-31 14:07
Looks like this is still an issue.  Very simple to confirm (see below).  Would love to get this fixed so it simply skips empty files.  Otherwise I have to pre-parse the file list to find non-empty files, which is a pain when you're using "goaccess *.log" (for instance).

```
# goaccess --version
GoAccess - 1.9.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2023 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
  --with-getline
  --with-openssl
# touch empty.log
# goaccess empty.log
Cleaning up resources...
==815424==
==815424== Format Errors - Verify your log/date/time format
#
# goaccess valid_log_file.log empty.log
Cleaning up resources...16} @ {0/s}                                                                                                                                                                                                 \
==815445==
==815445== Format Errors - Verify your log/date/time format
```

**Comment by allinurl** [comment] 2024-01-31 14:10
Thanks for letting me know; I find it intriguing that I overlooked addressing this issue. I'll take a look at it today and tomorrow, and I'll get back to you with an update.

**Comment by allinurl** [comment] 2024-02-02 02:32
I've committed changes to address this issue. It appears to be a regression, as testing in v1.8.1 showed it worked as expected. I'm not sure why I didn't close this issue earlier. In any event, please build from [**development**](https://github.com/allinurl/goaccess?tab=readme-ov-file#build-from-github-development) and confirm if the problem is resolved on your end. Thanks!

**Comment by everwatch** [comment] 2024-02-02 14:21
Since I'm deploying from Debian repos, it will be a bit before I can go build a development branch exe.  Will see how my work schedule goes today.

**Comment by ericloyd** [comment] 2024-02-02 15:00
Since I'm deploying from Debian repos, it will be a bit before I can go build a development branch exe. Will see how my work schedule goes today.

**Comment by ericloyd** [comment] 2024-02-02 15:59
After finally finding a box that had the right docker config, I created a new executable from the dev image and ran it against an empty log with no problem.   Seems like it was working in 1.8.1, so yeah, this looks good.

**Comment by allinurl** [comment] 2024-02-10 00:07
Thanks again for the update! Don't hesitate to reopen if necessary.

**Closed by allinurl** 2024-02-10 00:07 UTC
Labels: log-processing
