### ISSUE TITLE
Parsing stops after a while

### ISSUE THREAD

**Issue by wehmoen** [allinurl/goaccess#2381] opened 2022-09-14 15:31 UTC
Hi! 

I'm trying to parse an access log (format: COMBINED). After 447M lines the parsing stopped and the process seems to hang. The per second counter slowly decreases. This is the command I am running:

```
goaccess /data/log/pm2/data.rest-out.log -o 
/data/data/report.html --log-format=COMBINED 
--geoip-database /data/geo/dbip-country-lite-2022-09.mmdb 
--real-time-html 
--ssl-cert=/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/data/data.crt 
--ssl-key=/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/data/data.key 
--ws-url=data 
--restore 
--persist
```

It worked fine a few days ago. Not sure if the log file is simply too large.

**Comment by allinurl** [comment] 2022-09-14 15:34
Hi - what's the output of:

    # ls -lath /data/log/pm2/data.rest-out.log
and

    # wc -l /data/log/pm2/data.rest-out.log

**Comment by allinurl** [comment] 2022-09-14 15:35
+ your machine specs, e.g., ram, disk. Thanks

**Comment by wehmoen** [comment] 2022-09-14 19:10
`-rw-r--r-- 1 root root 109G Sep 14 21:08 /data/log/pm2/data.rest-out.log`

and

`475497212`

CPU: AMD Ryzen™ 9 5950X
Memory: 128GB
Storage: 3 x 4 TB NVME

There are plenty ressources available. Memory usage is only at ~60/128GB and CPU rarely exceeds 30%

**Comment by allinurl** [comment] 2022-09-15 00:07
Sounds do-able, a few questions for you:

1. Since you said that it worked fine a few days ago, I wonder, was that the first run? 
2. I'm curious if the issue is with `--restore` & `--persist`. Would you be able to run it without those two options?
3. What's a typical request from your log looks like? a lot of random requests or perhaps timestamped? 
    e.g.,  "GET https://url/allinurl/goaccess/issues/2381?ts=1663200271 HTTP2"

Thanks!

**Comment by wehmoen** [comment] 2022-09-15 07:29
1) Same log file just only half as many requests. 
2) I started a 2nd run without `--persist` & `--restore`. At first glance it is processing data much faster now
3) At the moment there are 5_286_517 lines that have query parameters. The majority of requests does not have timestamps.

**Comment by allinurl** [comment] 2022-09-22 00:17
Any updates regarding the second run?

**Comment by allinurl** [comment] 2022-11-24 02:53
Closing this. Feel free to reopen it if needed.

**Closed as completed by allinurl** 2022-11-24 02:53 UTC
Labels: question, log-processing
