### ISSUE TITLE
GoAccess 0.9.5 crashed by Signal 11

### ISSUE THREAD

**Issue by bugzorama** [allinurl/goaccess#323] opened 2015-10-23 13:22 UTC
1 - How was this encountered?

    /usr/local/bin/goaccess -f /var/log/httpd/access.log --debug-file debug.log --invalid-requests invalid.log --load-from-disk --keep-db-files 

It is working for only about 30-60 seconds and than

    ==528== GoAccess 0.9.5 crashed by Signal 11
    ==528==
    ==528== VALUES AT CRASH POINT
    ==528==
    ==528== Line number: 127079
    ==528== Offset: 126813
    ==528== Invalid data: 191 
    ==528== Piping: 0
    ==528== Response size: 7005259455 bytes
    ==528==
    ==528== STACK TRACE:
    ==528==
    ==528== 0 /usr/local/bin/goaccess(sigsegv_handler+0x8a) [0x40908d]
    ==528== 1 /lib64/libc.so.6(+0x326a0) [0x7f11e57d86a0]
    ==528== 2 /lib64/libc.so.6(+0x1283f6) [0x7f11e58ce3f6]
    ==528== 3 /usr/local/bin/goaccess(str2enum+0x3b) [0x407f75]
    ==528== 4 /usr/local/bin/goaccess(get_module_enum+0x22) [0x407fc0]
    ==528== 5 /usr/local/bin/goaccess(ignore_panel+0x35) [0x41c23f]
    ==528== 6 /usr/local/bin/goaccess() [0x40f324]
    ==528== 7 /usr/local/bin/goaccess() [0x4107e4]
    ==528== 8 /usr/local/bin/goaccess() [0x410e06]
    ==528== 9 /usr/local/bin/goaccess() [0x411003]
    ==528== 10 /usr/local/bin/goaccess(main+0x409) [0x411564]
    ==528== 11 /lib64/libc.so.6(__libc_start_main+0xfd) [0x7f11e57c4d5d]
    ==528== 12 /usr/local/bin/goaccess() [0x406469]
    ==528==
    ==528== Please report it by opening an issue on GitHub:
    ==528== https://github.com/allinurl/goaccess/issues

2 - What is your log format / sizes?

    ~30 MB

3 - What are libc versions you are currently using?

    glibc-2.12

4 - What is your OS?

    CentOS release 6.6

    Program received signal SIGSEGV, Segmentation fault.:
    0x00007ffff72c43f6 in __strcmp_sse42 () from /lib64/libc.so.6
    Missing separate debuginfos, use: debuginfo-install GeoIP-1.6.5-1.el6.x86_64 bzip2-libs-1.0.5-7.el6_0.x86_64 glibc-2.12-1.166.el6_7.3.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 tokyocabinet-1.4.33-6.el6.x86_64 zlib-1.2.3-29.el6.x86_64
    (gdb) bt
    #0  0x00007ffff72c43f6 in __strcmp_sse42 () from /lib64/libc.so.6
    #1  0x0000000000407f75 in str2enum (map=0x63b040, len=14, str=0xf600430102 <Address 0xf600430102 out of bounds>)
        at src/commons.c:123
    #2  0x0000000000407fc0 in get_module_enum (str=0xf600430102 <Address 0xf600430102 out of bounds>) at src/commons.c:137
    #3  0x000000000041c23f in ignore_panel (mod=VISITORS) at src/settings.c:385
    #4  0x000000000040f324 in allocate_data () at src/goaccess.c:193
    #5  0x00000000004107e4 in perform_tail_follow (size1=0x7fffffffe588) at src/goaccess.c:592
    #6  0x0000000000410e06 in get_keys () at src/goaccess.c:832
    #7  0x0000000000411003 in curses_output () at src/goaccess.c:892
    #8  0x0000000000411564 in main (argc=83, argv=0x640f20) at src/goaccess.c:1036

The same crash w/o tokyo :(

**Comment by aphorise** [comment] 2015-10-23 14:11
Duplicate of #322 - @bugzorama please close one of the tickets if you'd submitted both.

Out of interest - Is it possible that you can try updating you libc to a more recent version?
The on you are currently using seems to be from a period prior < 2013. 

I'm making some suggestion prior to the bosses (@allinurl) review.

**Comment by allinurl** [comment] 2015-10-23 14:14
Thanks for reporting this. Are you some ignoring panels? Could you please post your config file.

@aphorise thanks for pointing the libc thing, I'm looking into this.

**Comment by allinurl** [comment] 2015-10-23 17:27
Please try pulling from master. I believe this has been fixed. Let me know how it goes.

**Comment by allinurl** [comment] 2015-10-26 18:03
Closing since it is a duplicate from #327.

**Closed by allinurl** 2015-10-26 18:03 UTC
Labels: bug

**Comment by allinurl** [comment] 2015-10-27 01:27
This has been fixed. [v0.9.6](http://goaccess.io/) has been released which includes this fix.
