### ISSUE TITLE
Xforwarded logs apache

### ISSUE THREAD

**Issue by jhcos** [allinurl/goaccess#1193] opened 2018-08-08 01:28 UTC
Hi
Not able to get goaccess working get the below
```
# goaccess -f access_log --log-format=COMBINED
Parsed 10 lines producing the following errors:

Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
```

Log examples

```
192.168.52.10 - - [08/Aug/2018:11:26:14 +1000] "GET / HTTP/1.0" 301 232 "-" "-"
192.168.52.10 - - [08/Aug/2018:11:26:19 +1000] "GET / HTTP/1.0" 301 232 "-" "-"
192.168.52.10 - - [08/Aug/2018:11:26:24 +1000] "GET / HTTP/1.0" 301 232 "-" "-"
```
Log settings

```
    LogFormat "%{X-Forwarded-For}i %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    CustomLog "logs/access_log" combined env=!forwarded
    CustomLog "logs/access_log" proxy env=forwarded
    CustomLog "logs/access_log" combined
```

**Comment by allinurl** [comment] 2018-08-09 21:34
Please attach some additional lines from your log since I'm unable to reproduce this. If I run 

    goaccess test.log --log-format=COMBINED

Works fine from my end.

**Comment by allinurl** [comment] 2018-08-13 12:03
Are you running v1.2? Have you tried parsing the lines you posted above? For me 

    goaccess test.log --log-format=COMBINED

Works fine (assuming you don't have the first dash on each line). Also, please try using `--no-global-config`, e.g., 

    goaccess test.log --log-format=COMBINED --no-global-config

**Comment by allinurl** [comment] 2018-08-30 01:46
Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2018-08-30 01:46 UTC
Labels: log/date/time format, question
