### ISSUE TITLE
TLS parsing not working with mod_gnutls

### ISSUE THREAD

**Issue by Forza-tng** [allinurl/goaccess#2172] opened 2021-09-01 22:07 UTC
Hi!

I noticed that TLS parsing doesn't work with my Apache server. I'm using mod_gnutls and it outputs this in access.log

```
"TLS1.3" "ECDHE_RSA_CHACHA20_POLY1305"
```
Log-format is
```
log-format %v %h %^[%d %t.%f %^%^] "%r" %s %b "%K" "%k" "%R" "%u"
date-format %Y-%m-%d
time-format %H:%M:%S
```

Looking at #1967 I think there is a missing 'v' in TLS1. 3 and the cipher suites uses '_' instead of '-'.

**Comment by Forza-tng** [comment] 2021-09-03 15:03
I checked the source and it is indeed a simple string check for TLSv1. 1 etc.

**Comment by allinurl** [comment] 2021-09-14 01:03
Thanks for reporting this. Sorry a bit confused, are you saying the issue is related to `_` vs `-`?

**Comment by allinurl** [comment] 2021-09-14 01:19
okay so I just tried this and it's not outputting anything on that panel because of TLS1.3 not having the common `v` on it, e.g., TLSv1.3.

I could simply add TLS1.1 TLS1.2 TLS1.3  but I wonder what's the standard here... any thoughts?

**Comment by allinurl** [comment] 2021-09-23 02:48
I've added TLS1.1 TLS1.2 TLS1.3 to the list upstream. It will be pushed out in the upcoming release. Stay tuned.

Closing this. Feel free to reopen it if needed. Thanks

**Closed by allinurl** 2021-09-23 02:48 UTC
Labels: log-processing

**Comment by Forza-tng** [comment] 2021-09-23 03:57
> Thanks for reporting this. Sorry a bit confused, are you saying the issue is related to `_` vs `-`?

I originally thought that GoAccess also checked for the cipher suites. Openssl uses - in the names and gnutls uses _.

**Comment by allinurl** [comment] 2021-09-24 12:58
It does, but only when it's given as version of it, e.g., 

`"ciphersuite": 49196` resolves to `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384`
