### ISSUE TITLE
Weird problem with invalid data in html report

### ISSUE THREAD

**Issue by viktorminko** [allinurl/goaccess#887] opened 2017-09-19 22:42 UTC
Hi, 

thanks for a good logs analyzer. 

I'm using a configuration with 2 docker containers running together:

1. First container grabs Apache log file from remote server every minute and put it to shared volume.
2. Second container runs goaccess with that log file from shared volume in live-html mode. I'm using this image https://hub.docker.com/r/allinurl/goaccess/ 

Everything works fine at the beginning, report looks ok in the browser and is refreshed every minute with a few new records. 

The problem is that at some update round report receives a huge amount of new records, I think it somehow calculates some log records several times. I'm checking the log myself anf see that from some point of time the report doesn't correspond to the log anymore.

Any ideas where to check ?

**Comment by allinurl** [comment] 2017-09-20 00:50
Interesting, can you elaborate a bit more about on this part? 

> some point of time the report doesn't correspond to the log anymore.

Also, are you able to reproduce this starting with a much smaller access log and feed new lines to goaccess at a lower rate? Thanks

**Comment by viktorminko** [comment] 2017-09-20 16:52
I've tried 2 minutes interval in log update, issue still persists. 

Here is the command I'm using to grab log from remote host and use it in goaccess:

`ssh -o "StrictHostKeyChecking no" $REMOTE_USER@$REMOTE_HOST "tar czpf - $REMOTE_LOG_FILE" | tar xzpf - -C /home/logs --strip-components 3` 

I'm thinking it might be the case that goaccess tries to update the log while log file is not finished to download and as a result it adds some duplicated records. Is that possible ?

**Comment by allinurl** [comment] 2017-09-20 17:11
That could be very well the issue, especially if you are feeding the same log every x minutes. 

Now, if you are using the on-disk db, issue #334 should address the duplicate records, which by the way is in the works right now. Please take a look at the last post in there, a bash script that may help as a workaround. 

BTW, since you are ssh'ing into a remote machine, can you mount it with sshfs? or have you looked at `volumes-from`?

**Comment by viktorminko** [comment] 2017-09-20 17:59
@allinurl thanks, I will try workaround. My intension was to build everything on pure docker, sshfs can't be run in docker as far as I know, plugin is required.

**Comment by allinurl** [comment] 2017-09-20 18:05
@viktorminko also, take a look at Docker's `--volumes-from` option to grab the volume from another container and apply them to the current container, may do what you want without the need of the bash script.

**Comment by viktorminko** [comment] 2017-09-20 18:13
@allinurl Maybe my config is not clear for you. I will put it on github later, it might be useful for another people.  For my configuration there is no much difference if containers share volume from host or from another container, the problem is that goaccess reads the log file while it is not fully grabbed from remote machine. I will try to prevent goaccess to read log until its fully grabbed.

**Comment by allinurl** [comment] 2017-09-20 21:33
I see. For reference, it would be great if you could post your config. 

goaccess should be able to read a partial log even when it's still being fed with events. You can try tail -f the log while it's being pulled and see if there're dup records.

**Comment by viktorminko** [comment] 2017-11-22 14:03
Just uploaded my configuration here https://github.com/viktorminko/goaccess_docker_remote

Conserning the issue from this topic, check this file https://github.com/viktorminko/goaccess_docker_remote/blob/master/goaccess.sh around line 13 
I've added a sleep so container can wait for a few seconds to allow script in other container https://github.com/viktorminko/goaccess_docker_remote/blob/master/log_follower.sh to fully tail a log file. If I remove sleep then I will have duplicated entries in goaccess report.

**Comment by allinurl** [comment] 2017-11-22 22:30
Thanks for sharing that! It's certainly interesting to know about the `sleep(1)` call. It gives me some hints.

**Comment by allinurl** [comment] 2020-05-19 01:09
[**v1.4**](https://goaccess.io/download) addressed some issues with docker and its storage. Please give it a shot and feel free to share the results. Closing this for now.

**Closed by allinurl** 2020-05-19 01:09 UTC
Labels: docker, on-disk, websocket-server
