### ISSUE TITLE
Ubuntu package with GeoIP missing

### ISSUE THREAD

**Issue by jrossmann** [allinurl/goaccess#1191] opened 2018-08-06 08:31 UTC
Hi,

I installed the goaccess package on Ubuntu 18.04, but this does not seem to have GeoIP enabled:

  goaccess: unrecognized option '--geoip-database'

Is there a version with GeoIP avaliable?

Thx in advance

Jan

**Comment by allinurl** [comment] 2018-08-06 11:48
Did you use the official goaccess repo or the Ubuntu repo? The official goaccess' repo does come with geoip.

**Comment by jrossmann** [comment] 2018-08-06 11:53
I added the following to /etc/apt/sources.list.d/goaccess.list:
    deb http://deb.goaccess.io/ bionic main

So I assume I'm using the official goaccess repo

**Comment by moved-to-gitlab** [comment] 2018-08-11 20:36
I confirm the same problem after testing with a new Ubuntu 18.04 server, the `--geoip-database` option is unrecognised by GoAccess version 1.2 from the official GoAccess repository.

The contents of /etc/apt/sources.list.d/goaccess.list is:
```
deb http://deb.goaccess.io bionic main
```
Is there anything we can do to help test whatever Ubuntu 18.04 broke?

(as an aside, your TLS cert for your domain does not include the www subdomain, so previously tested and working links to your site break due to certificate mismatch errors)

**Comment by allinurl** [comment] 2018-08-13 11:59
@moved-to-gitlab I just tested this as well and I can confirm that too. I'll rebuild this package and post back, then I'll ask you to please help test it out. Thanks!

Thank you also for pointing the certificate issue. I'll look into it.

**Comment by allinurl** [comment] 2018-11-23 15:50
This should be fixed as v1.3 has been released. Thanks.

**Closed by allinurl** 2018-11-23 15:50 UTC
Labels: build, change, debian-repo
