### ISSUE TITLE
Missing data TX and T.S. values in web mode but present in json output and terminal

### ISSUE THREAD

**Issue by Dr-Escher** [allinurl/goaccess#1501] opened 2019-07-16 15:50 UTC
Missing data TX and T.S. values in web mode but present in json output and terminal

The traffic and timing data are missing in all tables, unlike in the goaccess live demo. However the values are present in the JSON output and shown in terminal mode as well. I tried several browsers including Firefox 68 and Chrome 75 without any noticeable differences.

Please take a look at the example below.

Any idea if this is this a bug or rather a configuration issue?

[goaccess.json.txt](https://github.com/allinurl/goaccess/files/3397938/goaccess.json.txt)

![cli](https://user-images.githubusercontent.com/48136347/61309200-08054c80-a7f2-11e9-85a3-a4bd55e33022.png)

![web](https://user-images.githubusercontent.com/48136347/61309206-09cf1000-a7f2-11e9-85a8-96e37be8e504.png)

**Comment by allinurl** [comment] 2019-07-16 15:53
Under "Panel Options", are these missing columns checked or unchecked? Thanks

**Comment by Dr-Escher** [comment] 2019-07-16 15:59
The plot metrics option seems to be missing at least one entry. The empty radiobox is not checkable.

All the other panel options are working as intended, including the three 'hits', 'visitors', 'data' columns.

![panel](https://user-images.githubusercontent.com/48136347/61309906-739be980-a7f3-11e9-98f8-1dd2856da3c6.png)

**Comment by allinurl** [comment] 2019-07-16 22:08
Could you please attach your config file and how you are running it? also, are you in v1.3? Thanks

**Comment by Dr-Escher** [comment] 2019-07-17 20:51
Usually I'm running a ssh pipe like

`ssh user@host 'zcat /var/log/nginx/access.log.{2..19}.gz; cat /var/log/nginx/access.log.1; tail -fn+1 /var/log/nginx/access.log' | goaccess -o /tmp/livereport.html -`

nginx log_format

`log_format custom '[$time_local] $remote_addr -> $remote_user@$host[$server_name] - "$request" = $status ($body_bytes_sent) "$http_referer" "$http_user_agent" $http2$https $ssl_cipher "$http_x_forwarded_for" $request_time ($upstream_connect_time|$upstream_header_time-$upstream_response_time)';`

goaccessrc
[goaccessrc.txt](https://github.com/allinurl/goaccess/files/3403799/goaccessrc.txt)

Tested using [goaccess 1.3](https://www.archlinux.org/packages/community/x86_64/goaccess/) from the Arch repository.

But while fiddling around and gathering information, I noticed this issue only exists when piping log data into goaccess to gather live statistics. Everything is fine if a static file is used as log input. This applies to both issues reported #1501 and #1502. This just works fine (same config and log file as above):

`goaccess -o /tmp/livereport.html access.log`

**Comment by allinurl** [comment] 2019-07-25 14:17
I can confirm this. It appears there's an issue while piping data in. Will look into this. Thanks for reporting it!

**Comment by allinurl** [comment] 2020-12-17 15:54
This has been fixed in the [**latest**](https://goaccess.io/download) version.

Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2020-12-17 15:54 UTC
Labels: bug, html report, log-processing, question

**Comment by aparajita** [comment] 2022-12-01 21:33
I'm seeing the same issue with version 1.6.5. I am tailing log files into a named pipe and using the named pipe as the input to goaccess. It's working as it should, but I am not seeing any of the T.S. columns even being available in the panel options.

**Comment by allinurl** [comment] 2022-12-02 01:25
@aparajita It looks like your log doesn't contain the request time. You will need to add that to your nginx config file (`$request_time`) so goaccess can start processing it (after adding the corresponding specifier `%T` to the goaccess' log-format variable). Let me know if that helps or if you have any additional questions.

By the way, if it's actually showing those columns on the UI, that may be a glitch on the report. Are you able to post a screenshot? Thanks.

**Comment by aparajita** [comment] 2022-12-02 01:34
@allinurl Thanks for the quick reply, I'll make that change and let you know what happens. Awesome tool!

And of course NOW I see the note in the docs:

> In order to get the average, cumulative and maximum time served in GoAccess, you will need to start logging response times in your web server. In Nginx you can add $request_time to your log format, or %D in Apache.

Doh! Sorry I missed that!

BTW, you might want to make it very obvious in the docs that we have to configure something _other_ than goaccess to serve the generated html report. Did I miss that?

**Comment by allinurl** [comment] 2022-12-02 02:01
There's a section at the bottom of the [**Get Started**](https://goaccess.io/get-started) page that highlights this. I wonder if we should add it somewhere else... Thoughts?

**Comment by aparajita** [comment] 2022-12-02 02:32
Hmm... I'm reading that and it isn't totally clear. I would suggest something like this:

---

Important
goaccess does NOT serve the generated html report. It is up to you to configure your web server to serve the generated report. You may wish to configure your web server to restrict access!

If the html report is generated locally, you can open it directly in your browser. In either case, once the report is open it will open a WebSocket to goaccess, which will push updates to the web page.

---

One other thing I just noticed: the brown background of "Important" notes actually discourages reading them! There have been studies that show that brown is the least favorite color. The eye unconsciously wants to look away. I would suggest reversing the color scheme in those notes (swap text/background colors). A yellow background will catch the eye much more effectively.

**Comment by aparajita** [comment] 2022-12-02 03:28
@allinurl Adding `$request_time` and `%T` fixed it, thank you! 🙏

**Comment by allinurl** [comment] 2022-12-04 18:42
@aparajita Glad that did the job. 

Made some updates to the get started page as you suggested. Also, thanks for the heads up on the colors, made minor updates as well. There's a site revamp coming in the pipeline as well so I'll make sure to take this into account.

**Comment by aparajita** [comment] 2022-12-04 20:42
Thanks for the great support @allinurl, I just donated.

**Comment by allinurl** [comment] 2022-12-04 21:02
@aparajita No problem, always happy to help :)

Thank you so much for the generous donation, much appreciated! Please stay tuned for some nice features coming in GoAccess.

**Comment by aparajita** [comment] 2022-12-04 22:03
Would love to see the ability to specify the order of panels.

**Comment by allinurl** [comment] 2022-12-04 23:13
I agree. I can look into adding an option to change the panels order.

**Comment by aparajita** [comment] 2022-12-05 02:25
While you're at it, it's currently quite confusing having both include panels and exclude panels. I could not figure out, even through experimentation, how they differ (other than being opposities). Wouldn't it be much simpler and more understandable to have only include, and to display them in the order they are listed there?

**Comment by allinurl** [comment] 2022-12-06 01:19
Not sure I follow. Do you mean `--include=PANEL_NAME` instead of --enable-panel=PANEL_NAME?

**Comment by aparajita** [comment] 2022-12-06 02:55
Yes, sorry, I wasn't looking at the config file. Seems to me that `--include-panel` is enough. Think about it: if a panel is not included, it sure can't be enabled. And if it isn't enabled, then including it is a no-op. As an end user, I'm just thinking: I want these panels to appear in this order. That's it. Make sense?

**Comment by allinurl** [comment] 2022-12-30 22:36
an FYI: Just pushed some changes that will address the issue where some metrics were missing on the HTML report when piping data in. [**Stay tuned**](https://twitter.com/goaccess) for the upcoming release.
