### ISSUE TITLE
zcat individual zip files pipe to go access and keep history

### ISSUE THREAD

**Issue by mandys** [allinurl/goaccess#1816] opened 2020-06-18 17:03 UTC
First of all thank you for a wonderful project.

Coming from Awstats which used to take very long ( sometimes hours ) to parse the log files, this is blazing fast :-)

I am trying to do the following:

Logs are under -

    /logs/files/<server_id>/<year>/<month>/varnish/varnishncsa.log.<date>.gz

eg:

```
/logs/files/aweb01/2020/06/varnish/varnishncsa.log.17.gz
/logs/files/aweb02/2020/06/varnish/varnishncsa.log.17.gz
```

Lets say I want to parse day before yesterdays logs ( 16th June ) which are now in .gz format, I do -

    zcat -f /logs/files/aweb01/2020/06/varnish/varnishncsa.log.16.gz /logs/files/aweb02/2020/06/varnish/varnishncsa.log.16.gz | /usr/local/bin/goaccess --log-format='~h{," } %v %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T  **--persist** -a -o /var/www/systems/report.html

Works great!

Then I want to append yesterdays logs to it

    zcat -f /logs/files/aweb01/2020/06/varnish/varnishncsa.log.17.gz /logs/files/aweb02/2020/06/varnish/varnishncsa.log.17.gz | /usr/local/bin/goaccess --log-format='~h{," } %v %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T **--restore --persist** -a -o /var/www/systems/report.html

Now, the results are not proper.

The report for 16th log files gives:

```
Total Requests
162,511

Valid Requests
162,509

Failed Requests
2
```

The report for 17th when run separately gives:

```
Total Requests
176,779

Valid Requests
176,779

Failed Requests
0
```

But, if I did the appending of daily data ( like mentioned above ) with persist and restore, my results are -

```
Total Requests
339,290

Valid Requests
205,594   --> This should have been 162,509 + 176,779 = 339288

Failed Requests
2
```

Why isn't it working properly ?

Running it again throws away the stats completely.
Duplicates happen, count keeps growing...

What am I doing wrong ?

Thanks in advance.

- Mandy

**Comment by allinurl** [comment] 2020-06-19 02:10
Glad you found it useful and thanks for reporting this. It is an interesting use case. I think the issue might be related to how goaccess keeps track of previous piped data. From the docs:

> GoAccess keeps track of inodes of all the files processed (assuming files will stay on the same partition) along with the last line parsed of each file and the timestamp of the last line parsed. e.g., inode:29627417|line:20012|ts:20171231235059
> 
> If the inode does not match the current file, it parses all lines. If the current file matches the inode, it then reads the remaining lines and updates the count of lines parsed and the timestamp. As an extra precaution, it won't parse log lines with a timestamp ≤ than the one stored.
> 
> **Piped data works based off the timestamp of the last line read. For instance, it will parse and discard all incoming entries until it finds a timestamp >= than the one stored.** Note that there could be overlapped lines in here.

Couple of questions for you:

1. Are you able to reproduce this with a much smaller dataset? For instance, adding a few lines and gzipped them and running goaccess the same. Essentially trying to recreate the same issue, but with a sample dataset containing < 100 lines.

2. For the sake of testing, are you able to extract those compressed logs into actual log files and parse them the same way but instead of piping data to it, simply passing them as access.logs. e.g., 

    goaccess access.log access.log.1 access.log.2 --persist --restore ...

**Comment by mandys** [comment] 2020-06-19 04:29
Thank you for your prompt response. I know you might be very busy but appreciate you jumping on this quickly. 

Quick update:

I unzipped the files and tried.

zcat -f /logs/files/aweb01/2020/06/varnish/varnishncsa.log.16 /logs/files/aweb02/2020/06/varnish/varnishncsa.log.16 | /usr/local/bin/goaccess --log-format='~h{," } %v %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T  --persist -a -o /var/www/systems/report.17.html

zcat -f /logs/files/aweb01/2020/06/varnish/varnishncsa.log.17 /logs/files/aweb02/2020/06/varnish/varnishncsa.log.17 | /usr/local/bin/goaccess --log-format='~h{," } %v %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T  --restore --persist -a -o /var/www/systems/report.17.html

Same result...ie, it DOES NOT work.

Then I tried what you suggested

/usr/local/bin/goaccess /logs/files/aweb01/2020/06/varnish/varnishncsa.log.16 /logs/files/aweb02/2020/06/varnish/varnishncsa.log.16 --log-format='~h{," } %v %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T  --persist -a -o /var/www/systems/report.17.html

/usr/local/bin/goaccess /logs/files/aweb01/2020/06/varnish/varnishncsa.log.17 /logs/files/aweb02/2020/06/varnish/varnishncsa.log.17 --log-format='~h{," } %v %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T  --restore --persist -a -o /var/www/systems/report.17.html

And Voila!
IT WORKS!!
:-)

It's a slight inconvenience that I would have to unzip yesterdays logs, run the above, then zip them back and keep them in cold storage. But, it works and I am grateful for that.
It's very fast! 

I was trying this on an aws t2.medium instance ( 4gb/2cpu box )
t2 series is an old series...

But, still I got 17000/s which is great. It took about 10-11 seconds to parse each server log.
The same logs took more than 30 minutes using awstats.

Thank you! Thank you!

**Comment by allinurl** [comment] 2020-07-08 22:08
That's the drawback of piping data since there is no reliable way that I can think to avoid some duplicates from the pipe. You can read more about this issue [here](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226) and how it was addressed. 

Closing this. Feel free to reopen it if needed.  Thanks for your feedback :)

**Closed by allinurl** 2020-07-08 22:08 UTC
Labels: log-processing
