### ISSUE TITLE
Error while running make command and building from Github

### ISSUE THREAD

**Issue by deosha** [allinurl/goaccess#721] opened 2017-04-07 06:23 UTC
I am getting below error while running make command while building it from git. I am able to do it when I get the code through wget. I am running it on ubuntu 14.04
```
./bin2c resources/tpls.html src/tpls.h tpls
./bin2c resources/css/bootstrap.min.css src/bootstrapcss.h bootstrap_css
./bin2c resources/css/fa.min.css src/facss.h fa_css
./bin2c resources/css/app.css src/appcss.h app_css
./bin2c resources/js/d3.v3.min.js src/d3js.h d3_js
./bin2c resources/js/hogan.min.js src/hoganjs.h hogan_js
./bin2c resources/js/charts.js src/chartsjs.h charts_js
./bin2c resources/js/app.js src/appjs.h app_js
make all-recursive
make[1]: Entering directory /home/ubuntu/goaccess' Making all in po make[2]: Entering directory/home/ubuntu/goaccess/po'
test ! -f ./goaccess.pot || 
test -z "fr.gmo" || make fr.gmo
make[3]: Entering directory /home/ubuntu/goaccess/po' rm -f fr.gmo && : -c --statistics --verbose -o fr.gmo fr.po mv: cannot stat ‘t-fr.gmo’: No such file or directory make[3]: *** [fr.gmo] Error 1 make[3]: Leaving directory/home/ubuntu/goaccess/po'
make[2]: *** [stamp-po] Error 2
make[2]: Leaving directory /home/ubuntu/goaccess/po' make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory/home/ubuntu/goaccess'
make: *** [all] Error 2
```

**Comment by allinurl** [comment] 2017-04-07 12:18
Do you have `gettext`installed?

    # apt-get install gettext

Then please run again:

```
$ autoreconf -fiv
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
# make install
```

**Comment by haricot** [comment] 2017-04-07 12:49
You may also need to install `autopoint` on debian based
`# apt-get install autopoint`
This is a necessary step for travis build debian based

**Comment by allinurl** [comment] 2017-04-11 00:34
Closing this. Feel free to reopen it if needed.

**Closed by allinurl** 2017-04-11 00:34 UTC
Labels: build, documentation

**Comment by OsirianOne** [comment] 2021-11-21 04:47
When running this 
sudo ./configure --enable-utf8 --enable-geoip=legacy

I get this:
checking for xmlto... no
checking for rst2man... no
./configure: line 8567: udev: command not found
checking for ANSI C header files... yes
./configure: line 8702: syntax error near unexpected token `NCURSESW,'
./configure: line 8702: `        PKG_CHECK_MODULES(NCURSESW, ncursesw,'

ncursesw5-dev is installed

**Comment by OsirianOne** [comment] 2021-11-21 08:55
> 

I think this was missed error just before this.
When trying to fix the cause of the error:
man autoconf

autoconf --help

neither explain where to add the line for m4_pattern_allow or how to use it in a switch for a command line,

ERROR:
configure.ac:44: error: possibly undefined macro: AC_CHECK_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:187: error: possibly undefined macro: AC_CHECK_PROG
autoreconf: /usr/bin/autoconf failed with exit status: 1
