### ISSUE TITLE
Docker and real time reporting Fifo error with websocket-server 

### ISSUE THREAD

**Issue by xbgmsharp** [allinurl/goaccess#861] opened 2017-08-08 10:44 UTC
Hello,

I try to run the docker image. It does work fine in ncurse mode. However when i enable the Websocket server with ``--real-time-html``  i got the following output with debug enable:
```
Unable to open fifo out: No such device or address.
WebSocket server ready to accept new client connections
```

From https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L304
Both options mention ``fifo-in``
```
# Path to read named pipe (FIFO).
#
#fifo-in /tmp/wspipein.fifo

# Path to write named pipe (FIFO).
#
#fifo-in /tmp/wspipeout.fifo
```

I try to run Docker with options ``--privileged`` but same result. 

Thanks,

**Comment by allinurl** [comment] 2017-08-08 12:08
Thanks for reporting this. Can I ask you to please try to uncomment those two options in your config file and see if the output changes? Thanks.

**Comment by xbgmsharp** [comment] 2017-08-08 12:27
I try with and without ``fifo-in`` and ``fifo-out`` as command line without any success.

**Comment by allinurl** [comment] 2017-08-09 04:16
I was playing with this but so far I've haven't been able to reproduce it. Assuming you used [this](https://github.com/allinurl/goaccess#docker) build, are you running docker as root? If not, can I ask you to please check if you still get the same error running it as root.

**Comment by xbgmsharp** [comment] 2017-08-09 10:15
That is correct, i am using your docker image with debug enable and SSL and GeoIP. Docker is running as root.

```
 git diff Dockerfile
diff --git a/Dockerfile b/Dockerfile
index cefa2ea..9637aca 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4,13 +4,13 @@ FROM alpine:edge
 COPY . /goaccess
 WORKDIR /goaccess
 
-ARG build_deps="build-base ncurses-dev autoconf automake git gettext-dev"
-ARG runtime_deps="tini ncurses libintl gettext "
+ARG build_deps="build-base ncurses-dev autoconf automake git gettext-dev libmaxminddb-dev openssl-dev"
+ARG runtime_deps="tini ncurses libintl gettext libmaxminddb openssl"
 
 RUN apk update && \
     apk add -u $runtime_deps $build_deps && \
     autoreconf -fiv && \
-    ./configure --enable-utf8 && \
+    ./configure --enable-utf8 --enable-geoip=mmdb --enable-debug --with-openssl && \
     make && \
     make install && \
     apk del $build_deps && \
```

**Comment by xbgmsharp** [comment] 2017-08-09 14:16
Even with the message "Unable to open fifo out: No such device or address.", it is working fine in SSL and non SSL.
```
Unable to open fifo out: No such device or address.
==Using TLS/SSL==
WebSocket server ready to accept new client connections
```

**Comment by allinurl** [comment] 2017-08-09 16:24
What do you mean with 'it is working fine in SSL and non SSL."? Are you able to take docker out of the picture and run it directly from your machine? I'm just curious if the issue is the result of running it within docker. Thanks.

**Comment by allinurl** [comment] 2017-08-15 01:30
Any update on this?

**Comment by allinurl** [comment] 2017-09-06 02:17
Closing this. Quoting from your previous post `it is working fine in SSL and non SSL`. Feel free to reopen it if needed.

**Closed by allinurl** 2017-09-06 02:17 UTC
Labels: docker, websocket-server

**Comment by allinurl** [comment] 2017-09-27 00:41
Just for the record, I just pushed a commit that should address `Unable to open fifo out: No such device or address.` using Docker.
