### ISSUE TITLE
Implement a command line argument to show the configure options at compile time

### ISSUE THREAD

**Issue by ms217** [allinurl/goaccess#940] opened 2017-11-09 13:50 UTC
As subject is suggesting it.
Afaik GoAccess doesn't support this. At least I haven't found this option in the latest stable 1.2 release.

An example with NGINX: I can check the configure arguments when I issue "nginx -V".
I need this for a GoAccess implementation into a webadministration panel.

**Comment by millsjustin** [comment] 2018-05-07 11:40
Duplicate of #1068.
Implemented in #1101.

**Comment by allinurl** [comment] 2018-05-07 11:42
Closing this. Thanks!

**Closed by allinurl** 2018-05-07 11:42 UTC
Labels: add, build, enhancement
