### ISSUE TITLE
Failed Requests number more than Total Requests

### ISSUE THREAD

**Issue by xiaolangit** [allinurl/goaccess#295] opened 2015-09-06 11:33 UTC
![image](https://cloud.githubusercontent.com/assets/8486029/9703837/2df60b96-54c2-11e5-8a39-31258a654450.png)

nginx log format conf:
            '$remote_addr [$time_local] $request $http_host '
            '$status $body_bytes_sent $http_referer $request_body '
             '$http_x_forwarded_for $upstream_addr $upstream_status '
             '$upstream_cache_status $upstream_response_time $request_time "$http_user_agent"';

nginx log:

    58.212.142.xx [17/Aug/2015:00:04:53 +0800] GET /dxxx.htm HTTP/1.1 xx 200 30164 http://www.xx.com/xxx.htm - - 172.16.9.52:80 200 - 0.137 0.137 "Mozilla/5.0 (Win
dows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 SE 2.X MetaSr 1.0"

cat ~/.goaccessrc

    time-format %T
    date-format %d/%b/%Y
    log-format %h [%d:%t %^] %m %U %H %^ %s %b %R %^ %^ %^ %^ %^ %^ %T "%u"

Help to look at the format configuration

why are the requests failed ?   

In Goaccess Code. How to tell the requests are failed? I want to search these failed requests in my log.But the log is too large.  

Thank for your help !

**Comment by allinurl** [comment] 2015-09-06 22:13
The sample log you posted works fine with log/date/time format posted. It could be that your `%R` referer is not properly delimited.

I just added the ability to log all invalid requests to a file using `--invalid-requests=<filename>`. You will need to build from [dev](http://goaccess.io/download#build).

Let me know how it goes. Thanks

**Comment by xiaolangit** [comment] 2015-09-07 05:54
When I install the Goaccess from the source code. I met a trouble:
$ git clone https://github.com/allinurl/goaccess.git
$ cd goaccess
$ autoreconf -fi
$ ./configure --invalid-requests=/data/filename

output the error:
configure: error: unrecognized option: --invalid-requests=/data/filename
Try `./configure --help' for more information.

**Comment by allinurl** [comment] 2015-09-07 06:02
$ git clone https://github.com/allinurl/goaccess.git
    $ cd goaccess
    $ autoreconf -fi
    $ ./configure --enable-geoip --enable-utf8
    $ make
    # make install

**Comment by allinurl** [comment] 2015-09-07 06:04
After installing,

    goaccess -f access.log -p ~/.goaccessrc --invalid-requests=/data/filename

**Comment by xiaolangit** [comment] 2015-09-07 11:29
A lot of post requests in invalid requests file.  Many people posting in website in chinise. The invalid request file is 5% of the nginx log.May be this is not the problem you said.

The same env, same config . The problem of recent logs analysis.  
![w5b8347eo uo1a96m nb 6](https://cloud.githubusercontent.com/assets/8486029/9715711/b35e2a24-5595-11e5-9187-72168fa6985a.png)
![i3l q xei isrmtb69f0e](https://cloud.githubusercontent.com/assets/8486029/9715714/bf214940-5595-11e5-8af7-0e529f667df2.png)

Thanks a lot.

**Comment by allinurl** [comment] 2015-09-07 14:58
Feel free to post some invalid requests and the log format that you are using to see why they're failing.

**Comment by xiaolangit** [comment] 2015-09-08 02:18
This a piece of invalid log:

%88%A9%E9%99%8C%E7%94%9F%E4%BA%86VmUkDW&token=xxxxx&uid=31864030 52.186.173.222 172.16.8.142:80 200 - 0.297 0.328 "Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0"

**Comment by allinurl** [comment] 2015-09-08 02:31
@xiaolangit is that the whole line?

**Comment by xiaolangit** [comment] 2015-09-08 02:33
YES. This is Post request.

**Comment by allinurl** [comment] 2015-09-08 02:41
Looks like the issue is due to inconsistent requests throughout your log. The last sample line you posted does not contain a date plus some missing identifiers. You may want to look into why you are getting different set of hits.

Closing this, feel free to reopen it if needed.

**Closed by allinurl** 2015-09-08 02:41 UTC
Labels: question
